// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fire_zone.proto

package fireZone

import (
	action "biostar/service/action"
	device "biostar/service/device"
	zone "biostar/service/zone"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FireSensor struct {
	DeviceID             uint32            `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Port                 uint32            `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type                 device.SwitchType `protobuf:"varint,3,opt,name=type,proto3,enum=device.SwitchType" json:"type,omitempty"`
	Duration             uint32            `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FireSensor) Reset()         { *m = FireSensor{} }
func (m *FireSensor) String() string { return proto.CompactTextString(m) }
func (*FireSensor) ProtoMessage()    {}
func (*FireSensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{0}
}

func (m *FireSensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FireSensor.Unmarshal(m, b)
}
func (m *FireSensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FireSensor.Marshal(b, m, deterministic)
}
func (m *FireSensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FireSensor.Merge(m, src)
}
func (m *FireSensor) XXX_Size() int {
	return xxx_messageInfo_FireSensor.Size(m)
}
func (m *FireSensor) XXX_DiscardUnknown() {
	xxx_messageInfo_FireSensor.DiscardUnknown(m)
}

var xxx_messageInfo_FireSensor proto.InternalMessageInfo

func (m *FireSensor) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *FireSensor) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *FireSensor) GetType() device.SwitchType {
	if m != nil {
		return m.Type
	}
	return device.SwitchType_NORMALLY_OPEN
}

func (m *FireSensor) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type ZoneInfo struct {
	ZoneID               uint32           `protobuf:"varint,1,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Disabled             bool             `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Alarmed              bool             `protobuf:"varint,4,opt,name=alarmed,proto3" json:"alarmed,omitempty"`
	DoorIDs              []uint32         `protobuf:"varint,5,rep,packed,name=doorIDs,proto3" json:"doorIDs,omitempty"`
	Sensors              []*FireSensor    `protobuf:"bytes,6,rep,name=sensors,proto3" json:"sensors,omitempty"`
	Actions              []*action.Action `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ZoneInfo) Reset()         { *m = ZoneInfo{} }
func (m *ZoneInfo) String() string { return proto.CompactTextString(m) }
func (*ZoneInfo) ProtoMessage()    {}
func (*ZoneInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{1}
}

func (m *ZoneInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneInfo.Unmarshal(m, b)
}
func (m *ZoneInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneInfo.Marshal(b, m, deterministic)
}
func (m *ZoneInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneInfo.Merge(m, src)
}
func (m *ZoneInfo) XXX_Size() int {
	return xxx_messageInfo_ZoneInfo.Size(m)
}
func (m *ZoneInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneInfo proto.InternalMessageInfo

func (m *ZoneInfo) GetZoneID() uint32 {
	if m != nil {
		return m.ZoneID
	}
	return 0
}

func (m *ZoneInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ZoneInfo) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *ZoneInfo) GetAlarmed() bool {
	if m != nil {
		return m.Alarmed
	}
	return false
}

func (m *ZoneInfo) GetDoorIDs() []uint32 {
	if m != nil {
		return m.DoorIDs
	}
	return nil
}

func (m *ZoneInfo) GetSensors() []*FireSensor {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *ZoneInfo) GetActions() []*action.Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type GetRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetResponse struct {
	Zones                []*ZoneInfo `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetZones() []*ZoneInfo {
	if m != nil {
		return m.Zones
	}
	return nil
}

type GetStatusRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneIDs              []uint32 `protobuf:"varint,2,rep,packed,name=zoneIDs,proto3" json:"zoneIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{4}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

func (m *GetStatusRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *GetStatusRequest) GetZoneIDs() []uint32 {
	if m != nil {
		return m.ZoneIDs
	}
	return nil
}

type GetStatusResponse struct {
	Status               []*zone.ZoneStatus `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{5}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetStatus() []*zone.ZoneStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type AddRequest struct {
	DeviceID             uint32      `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Zones                []*ZoneInfo `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{6}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *AddRequest) GetZones() []*ZoneInfo {
	if m != nil {
		return m.Zones
	}
	return nil
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{7}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

type DeleteRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneIDs              []uint32 `protobuf:"varint,2,rep,packed,name=zoneIDs,proto3" json:"zoneIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *DeleteRequest) GetZoneIDs() []uint32 {
	if m != nil {
		return m.ZoneIDs
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type DeleteAllRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllRequest) Reset()         { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()    {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{10}
}

func (m *DeleteAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllRequest.Unmarshal(m, b)
}
func (m *DeleteAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllRequest.Merge(m, src)
}
func (m *DeleteAllRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllRequest.Size(m)
}
func (m *DeleteAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllRequest proto.InternalMessageInfo

func (m *DeleteAllRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type DeleteAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllResponse) Reset()         { *m = DeleteAllResponse{} }
func (m *DeleteAllResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllResponse) ProtoMessage()    {}
func (*DeleteAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{11}
}

func (m *DeleteAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllResponse.Unmarshal(m, b)
}
func (m *DeleteAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllResponse.Merge(m, src)
}
func (m *DeleteAllResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllResponse.Size(m)
}
func (m *DeleteAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllResponse proto.InternalMessageInfo

type SetAlarmRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneIDs              []uint32 `protobuf:"varint,2,rep,packed,name=zoneIDs,proto3" json:"zoneIDs,omitempty"`
	Alarmed              bool     `protobuf:"varint,3,opt,name=alarmed,proto3" json:"alarmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmRequest) Reset()         { *m = SetAlarmRequest{} }
func (m *SetAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*SetAlarmRequest) ProtoMessage()    {}
func (*SetAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{12}
}

func (m *SetAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmRequest.Unmarshal(m, b)
}
func (m *SetAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmRequest.Marshal(b, m, deterministic)
}
func (m *SetAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmRequest.Merge(m, src)
}
func (m *SetAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_SetAlarmRequest.Size(m)
}
func (m *SetAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmRequest proto.InternalMessageInfo

func (m *SetAlarmRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetAlarmRequest) GetZoneIDs() []uint32 {
	if m != nil {
		return m.ZoneIDs
	}
	return nil
}

func (m *SetAlarmRequest) GetAlarmed() bool {
	if m != nil {
		return m.Alarmed
	}
	return false
}

type SetAlarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmResponse) Reset()         { *m = SetAlarmResponse{} }
func (m *SetAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*SetAlarmResponse) ProtoMessage()    {}
func (*SetAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf36a4b81e4bb96, []int{13}
}

func (m *SetAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmResponse.Unmarshal(m, b)
}
func (m *SetAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmResponse.Marshal(b, m, deterministic)
}
func (m *SetAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmResponse.Merge(m, src)
}
func (m *SetAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_SetAlarmResponse.Size(m)
}
func (m *SetAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FireSensor)(nil), "fire_zone.FireSensor")
	proto.RegisterType((*ZoneInfo)(nil), "fire_zone.ZoneInfo")
	proto.RegisterType((*GetRequest)(nil), "fire_zone.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "fire_zone.GetResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "fire_zone.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "fire_zone.GetStatusResponse")
	proto.RegisterType((*AddRequest)(nil), "fire_zone.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "fire_zone.AddResponse")
	proto.RegisterType((*DeleteRequest)(nil), "fire_zone.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "fire_zone.DeleteResponse")
	proto.RegisterType((*DeleteAllRequest)(nil), "fire_zone.DeleteAllRequest")
	proto.RegisterType((*DeleteAllResponse)(nil), "fire_zone.DeleteAllResponse")
	proto.RegisterType((*SetAlarmRequest)(nil), "fire_zone.SetAlarmRequest")
	proto.RegisterType((*SetAlarmResponse)(nil), "fire_zone.SetAlarmResponse")
}

func init() { proto.RegisterFile("fire_zone.proto", fileDescriptor_0bf36a4b81e4bb96) }

var fileDescriptor_0bf36a4b81e4bb96 = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0xe3, 0x34, 0x8f, 0x1b, 0x92, 0xa6, 0x53, 0x51, 0x0d, 0x6e, 0x17, 0x91, 0x17, 0xc8,
	0x6c, 0x1c, 0x29, 0x74, 0x81, 0x90, 0xba, 0x08, 0x84, 0x86, 0xec, 0x90, 0xc3, 0xaa, 0x1b, 0xe4,
	0xc4, 0xb7, 0xc2, 0x22, 0xf1, 0x98, 0x99, 0x09, 0xa8, 0xac, 0xf8, 0x03, 0xbe, 0x91, 0x3f, 0x41,
	0x33, 0x1e, 0xbf, 0x42, 0x04, 0x91, 0xba, 0x8a, 0xef, 0xc3, 0xe7, 0x1c, 0x9f, 0x73, 0x15, 0x38,
	0xbd, 0x8f, 0x39, 0x7e, 0xfa, 0xc1, 0x12, 0xf4, 0x53, 0xce, 0x24, 0x23, 0xdd, 0xa2, 0xe1, 0x40,
	0xd9, 0x76, 0x9e, 0x84, 0x6b, 0x19, 0xb3, 0x24, 0xaf, 0x22, 0xfc, 0x16, 0xaf, 0xcd, 0xcc, 0xfd,
	0x69, 0x01, 0xdc, 0xc6, 0x1c, 0x97, 0x98, 0x08, 0xc6, 0x89, 0x03, 0x9d, 0x6c, 0xbc, 0x98, 0x51,
	0x6b, 0x64, 0x79, 0xfd, 0xa0, 0xa8, 0x09, 0x81, 0x66, 0xca, 0xb8, 0xa4, 0x0d, 0xdd, 0xd7, 0xcf,
	0xe4, 0x39, 0x34, 0xe5, 0x43, 0x8a, 0xd4, 0x1e, 0x59, 0xde, 0x60, 0x42, 0x7c, 0x83, 0xbd, 0xfc,
	0x1e, 0xcb, 0xf5, 0xe7, 0x8f, 0x0f, 0x29, 0x06, 0x7a, 0xae, 0x71, 0x77, 0x3c, 0x54, 0x32, 0x68,
	0xd3, 0xe0, 0x9a, 0xda, 0xfd, 0x6d, 0x41, 0xe7, 0x8e, 0x25, 0xb8, 0x48, 0xee, 0x19, 0xb9, 0x80,
	0x96, 0x52, 0x5e, 0xd0, 0x9b, 0x4a, 0x91, 0x27, 0xe1, 0x16, 0x35, 0x79, 0x37, 0xd0, 0xcf, 0x1a,
	0x34, 0x16, 0xe1, 0x6a, 0x83, 0x91, 0x16, 0xd0, 0x09, 0x8a, 0x9a, 0x50, 0x68, 0x87, 0x9b, 0x90,
	0x6f, 0x31, 0xd2, 0x7c, 0x9d, 0x20, 0x2f, 0xd5, 0x24, 0x62, 0x8c, 0x2f, 0x66, 0x82, 0x9e, 0x8c,
	0x6c, 0xaf, 0x1f, 0xe4, 0x25, 0x19, 0x43, 0x5b, 0x68, 0x1b, 0x04, 0x6d, 0x8d, 0x6c, 0xaf, 0x37,
	0x79, 0xea, 0x97, 0x0e, 0x97, 0x26, 0x05, 0xf9, 0x16, 0xf1, 0xa0, 0x9d, 0x59, 0x2b, 0x68, 0x5b,
	0xbf, 0x30, 0xf0, 0x8d, 0xd5, 0x53, 0xfd, 0x13, 0xe4, 0x63, 0xd7, 0x03, 0x98, 0xa3, 0x0c, 0xf0,
	0xeb, 0x0e, 0x85, 0xfc, 0x97, 0xcb, 0xee, 0x2b, 0xe8, 0xe9, 0x4d, 0x91, 0xb2, 0x44, 0x20, 0x79,
	0x01, 0x27, 0x8a, 0x5e, 0x50, 0x4b, 0x13, 0x9c, 0x57, 0x14, 0xe5, 0x9e, 0x05, 0xd9, 0x86, 0xfb,
	0x1e, 0x86, 0x73, 0x94, 0x4b, 0x19, 0xca, 0x9d, 0x38, 0x82, 0x49, 0x19, 0x91, 0x99, 0x2b, 0x68,
	0x23, 0x33, 0xc2, 0x94, 0xee, 0x0d, 0x9c, 0x55, 0x90, 0x8c, 0x12, 0x0f, 0x5a, 0x42, 0x77, 0x8c,
	0x94, 0xa1, 0x5f, 0xa8, 0x30, 0x9b, 0x66, 0xee, 0x2e, 0x01, 0xa6, 0x51, 0x74, 0x8c, 0x84, 0xe2,
	0xeb, 0x1a, 0xff, 0xfd, 0xba, 0x3e, 0xf4, 0x34, 0x68, 0xa6, 0xc6, 0x7d, 0x07, 0xfd, 0x19, 0x6e,
	0x50, 0xe2, 0xe3, 0xbe, 0x74, 0x08, 0x83, 0x1c, 0xc6, 0x00, 0xfb, 0x30, 0xcc, 0x3a, 0xd3, 0xcd,
	0xe6, 0x98, 0xbc, 0xce, 0xe1, 0xac, 0xb2, 0x6f, 0x40, 0x42, 0x38, 0x5d, 0xa2, 0x9c, 0xaa, 0x8b,
	0x7b, 0x94, 0xbe, 0xea, 0x19, 0xdb, 0xb5, 0x33, 0x76, 0x09, 0x0c, 0x4b, 0x8a, 0x8c, 0x76, 0xf2,
	0xcb, 0x86, 0xbe, 0xba, 0x53, 0xdd, 0x55, 0x06, 0x92, 0x6b, 0xb0, 0xe7, 0x28, 0x49, 0xf5, 0x90,
	0xcb, 0x3b, 0x74, 0x2e, 0xf6, 0xdb, 0x26, 0xea, 0x5b, 0xe8, 0x16, 0xf9, 0x93, 0xcb, 0xfa, 0x52,
	0xed, 0xbe, 0x9c, 0xab, 0xc3, 0x43, 0x83, 0x73, 0x0d, 0xf6, 0x34, 0x8a, 0x6a, 0xec, 0xe5, 0x61,
	0xd4, 0xd8, 0x2b, 0xd1, 0x92, 0x1b, 0x68, 0x65, 0x8e, 0x12, 0x5a, 0xd9, 0xa8, 0xa5, 0xed, 0x3c,
	0x3b, 0x30, 0x29, 0xc5, 0x17, 0x81, 0xd4, 0xc4, 0xef, 0xc7, 0x5a, 0x13, 0xff, 0x57, 0x86, 0xe4,
	0x2d, 0x74, 0x72, 0x83, 0x89, 0x53, 0xd9, 0xdc, 0x0b, 0xd6, 0xb9, 0x3c, 0x38, 0xcb, 0x40, 0xde,
	0xbc, 0x86, 0xab, 0x35, 0xdb, 0xfa, 0x62, 0x97, 0x72, 0xdc, 0x86, 0x71, 0xb2, 0xf6, 0x45, 0xf4,
	0xa5, 0x7c, 0xe1, 0x83, 0x75, 0x47, 0x57, 0x31, 0x13, 0x32, 0xe4, 0x63, 0x81, 0x5c, 0x9d, 0xc3,
	0x58, 0x0d, 0x55, 0x76, 0xab, 0x96, 0xfe, 0x87, 0x7e, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x28,
	0x5c, 0x66, 0xa6, 0xe7, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FireAlarmZoneClient is the client API for FireAlarmZone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FireAlarmZoneClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error)
	SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error)
}

type fireAlarmZoneClient struct {
	cc *grpc.ClientConn
}

func NewFireAlarmZoneClient(cc *grpc.ClientConn) FireAlarmZoneClient {
	return &fireAlarmZoneClient{cc}
}

func (c *fireAlarmZoneClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/fire_zone.FireAlarmZone/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fireAlarmZoneClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/fire_zone.FireAlarmZone/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fireAlarmZoneClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/fire_zone.FireAlarmZone/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fireAlarmZoneClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/fire_zone.FireAlarmZone/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fireAlarmZoneClient) DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error) {
	out := new(DeleteAllResponse)
	err := c.cc.Invoke(ctx, "/fire_zone.FireAlarmZone/DeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fireAlarmZoneClient) SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error) {
	out := new(SetAlarmResponse)
	err := c.cc.Invoke(ctx, "/fire_zone.FireAlarmZone/SetAlarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FireAlarmZoneServer is the server API for FireAlarmZone service.
type FireAlarmZoneServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteAll(context.Context, *DeleteAllRequest) (*DeleteAllResponse, error)
	SetAlarm(context.Context, *SetAlarmRequest) (*SetAlarmResponse, error)
}

func RegisterFireAlarmZoneServer(s *grpc.Server, srv FireAlarmZoneServer) {
	s.RegisterService(&_FireAlarmZone_serviceDesc, srv)
}

func _FireAlarmZone_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FireAlarmZoneServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fire_zone.FireAlarmZone/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FireAlarmZoneServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FireAlarmZone_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FireAlarmZoneServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fire_zone.FireAlarmZone/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FireAlarmZoneServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FireAlarmZone_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FireAlarmZoneServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fire_zone.FireAlarmZone/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FireAlarmZoneServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FireAlarmZone_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FireAlarmZoneServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fire_zone.FireAlarmZone/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FireAlarmZoneServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FireAlarmZone_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FireAlarmZoneServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fire_zone.FireAlarmZone/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FireAlarmZoneServer).DeleteAll(ctx, req.(*DeleteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FireAlarmZone_SetAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FireAlarmZoneServer).SetAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fire_zone.FireAlarmZone/SetAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FireAlarmZoneServer).SetAlarm(ctx, req.(*SetAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FireAlarmZone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fire_zone.FireAlarmZone",
	HandlerType: (*FireAlarmZoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _FireAlarmZone_Get_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _FireAlarmZone_GetStatus_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _FireAlarmZone_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FireAlarmZone_Delete_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _FireAlarmZone_DeleteAll_Handler,
		},
		{
			MethodName: "SetAlarm",
			Handler:    _FireAlarmZone_SetAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fire_zone.proto",
}
