// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lift.proto

package lift

import (
	action "biostar/service/action"
	device "biostar/service/device"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FloorFlag int32

const (
	FloorFlag_NONE      FloorFlag = 0
	FloorFlag_SCHEDULE  FloorFlag = 1
	FloorFlag_OPERATOR  FloorFlag = 4
	FloorFlag_ACTION    FloorFlag = 8
	FloorFlag_EMERGENCY FloorFlag = 2
)

var FloorFlag_name = map[int32]string{
	0: "NONE",
	1: "SCHEDULE",
	4: "OPERATOR",
	8: "ACTION",
	2: "EMERGENCY",
}

var FloorFlag_value = map[string]int32{
	"NONE":      0,
	"SCHEDULE":  1,
	"OPERATOR":  4,
	"ACTION":    8,
	"EMERGENCY": 2,
}

func (x FloorFlag) String() string {
	return proto.EnumName(FloorFlag_name, int32(x))
}

func (FloorFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{0}
}

type AlarmFlag int32

const (
	AlarmFlag_NO_ALARM AlarmFlag = 0
	AlarmFlag_FIRST    AlarmFlag = 1
	AlarmFlag_SECOND   AlarmFlag = 2
	AlarmFlag_TAMPER   AlarmFlag = 4
)

var AlarmFlag_name = map[int32]string{
	0: "NO_ALARM",
	1: "FIRST",
	2: "SECOND",
	4: "TAMPER",
}

var AlarmFlag_value = map[string]int32{
	"NO_ALARM": 0,
	"FIRST":    1,
	"SECOND":   2,
	"TAMPER":   4,
}

func (x AlarmFlag) String() string {
	return proto.EnumName(AlarmFlag_name, int32(x))
}

func (AlarmFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{1}
}

type DualAuthApprovalType int32

const (
	DualAuthApprovalType_NONE_ON_LIFT DualAuthApprovalType = 0
	DualAuthApprovalType_LAST_ON_LIFT DualAuthApprovalType = 1
)

var DualAuthApprovalType_name = map[int32]string{
	0: "NONE_ON_LIFT",
	1: "LAST_ON_LIFT",
}

var DualAuthApprovalType_value = map[string]int32{
	"NONE_ON_LIFT": 0,
	"LAST_ON_LIFT": 1,
}

func (x DualAuthApprovalType) String() string {
	return proto.EnumName(DualAuthApprovalType_name, int32(x))
}

func (DualAuthApprovalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{2}
}

type FloorStatus struct {
	Activated            bool     `protobuf:"varint,1,opt,name=activated,proto3" json:"activated,omitempty"`
	ActivateFlags        uint32   `protobuf:"varint,2,opt,name=activateFlags,proto3" json:"activateFlags,omitempty"`
	DeactivateFlags      uint32   `protobuf:"varint,3,opt,name=deactivateFlags,proto3" json:"deactivateFlags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FloorStatus) Reset()         { *m = FloorStatus{} }
func (m *FloorStatus) String() string { return proto.CompactTextString(m) }
func (*FloorStatus) ProtoMessage()    {}
func (*FloorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{0}
}

func (m *FloorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloorStatus.Unmarshal(m, b)
}
func (m *FloorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloorStatus.Marshal(b, m, deterministic)
}
func (m *FloorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloorStatus.Merge(m, src)
}
func (m *FloorStatus) XXX_Size() int {
	return xxx_messageInfo_FloorStatus.Size(m)
}
func (m *FloorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FloorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FloorStatus proto.InternalMessageInfo

func (m *FloorStatus) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

func (m *FloorStatus) GetActivateFlags() uint32 {
	if m != nil {
		return m.ActivateFlags
	}
	return 0
}

func (m *FloorStatus) GetDeactivateFlags() uint32 {
	if m != nil {
		return m.DeactivateFlags
	}
	return 0
}

type Floor struct {
	DeviceID             uint32       `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Port                 uint32       `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Status               *FloorStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Floor) Reset()         { *m = Floor{} }
func (m *Floor) String() string { return proto.CompactTextString(m) }
func (*Floor) ProtoMessage()    {}
func (*Floor) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{1}
}

func (m *Floor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Floor.Unmarshal(m, b)
}
func (m *Floor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Floor.Marshal(b, m, deterministic)
}
func (m *Floor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Floor.Merge(m, src)
}
func (m *Floor) XXX_Size() int {
	return xxx_messageInfo_Floor.Size(m)
}
func (m *Floor) XXX_DiscardUnknown() {
	xxx_messageInfo_Floor.DiscardUnknown(m)
}

var xxx_messageInfo_Floor proto.InternalMessageInfo

func (m *Floor) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *Floor) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Floor) GetStatus() *FloorStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Sensor struct {
	DeviceID             uint32            `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Port                 uint32            `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type                 device.SwitchType `protobuf:"varint,3,opt,name=type,proto3,enum=device.SwitchType" json:"type,omitempty"`
	Duration             uint32            `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	ScheduleID           uint32            `protobuf:"varint,5,opt,name=scheduleID,proto3" json:"scheduleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Sensor) Reset()         { *m = Sensor{} }
func (m *Sensor) String() string { return proto.CompactTextString(m) }
func (*Sensor) ProtoMessage()    {}
func (*Sensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{2}
}

func (m *Sensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sensor.Unmarshal(m, b)
}
func (m *Sensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sensor.Marshal(b, m, deterministic)
}
func (m *Sensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sensor.Merge(m, src)
}
func (m *Sensor) XXX_Size() int {
	return xxx_messageInfo_Sensor.Size(m)
}
func (m *Sensor) XXX_DiscardUnknown() {
	xxx_messageInfo_Sensor.DiscardUnknown(m)
}

var xxx_messageInfo_Sensor proto.InternalMessageInfo

func (m *Sensor) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *Sensor) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Sensor) GetType() device.SwitchType {
	if m != nil {
		return m.Type
	}
	return device.SwitchType_NORMALLY_OPEN
}

func (m *Sensor) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Sensor) GetScheduleID() uint32 {
	if m != nil {
		return m.ScheduleID
	}
	return 0
}

type Alarm struct {
	Sensor               *Sensor        `protobuf:"bytes,1,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Action               *action.Action `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Alarm) Reset()         { *m = Alarm{} }
func (m *Alarm) String() string { return proto.CompactTextString(m) }
func (*Alarm) ProtoMessage()    {}
func (*Alarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{3}
}

func (m *Alarm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alarm.Unmarshal(m, b)
}
func (m *Alarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alarm.Marshal(b, m, deterministic)
}
func (m *Alarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alarm.Merge(m, src)
}
func (m *Alarm) XXX_Size() int {
	return xxx_messageInfo_Alarm.Size(m)
}
func (m *Alarm) XXX_DiscardUnknown() {
	xxx_messageInfo_Alarm.DiscardUnknown(m)
}

var xxx_messageInfo_Alarm proto.InternalMessageInfo

func (m *Alarm) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *Alarm) GetAction() *action.Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type Status struct {
	LiftID               uint32         `protobuf:"varint,1,opt,name=liftID,proto3" json:"liftID,omitempty"`
	AlarmFlags           uint32         `protobuf:"varint,2,opt,name=alarmFlags,proto3" json:"alarmFlags,omitempty"`
	TamperOn             bool           `protobuf:"varint,3,opt,name=tamperOn,proto3" json:"tamperOn,omitempty"`
	Floors               []*FloorStatus `protobuf:"bytes,4,rep,name=floors,proto3" json:"floors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{4}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetLiftID() uint32 {
	if m != nil {
		return m.LiftID
	}
	return 0
}

func (m *Status) GetAlarmFlags() uint32 {
	if m != nil {
		return m.AlarmFlags
	}
	return 0
}

func (m *Status) GetTamperOn() bool {
	if m != nil {
		return m.TamperOn
	}
	return false
}

func (m *Status) GetFloors() []*FloorStatus {
	if m != nil {
		return m.Floors
	}
	return nil
}

type LiftInfo struct {
	LiftID                    uint32               `protobuf:"varint,1,opt,name=liftID,proto3" json:"liftID,omitempty"`
	Name                      string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeviceIDs                 []uint32             `protobuf:"varint,3,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	ActivateTimeout           uint32               `protobuf:"varint,4,opt,name=activateTimeout,proto3" json:"activateTimeout,omitempty"`
	DualAuthTimeout           uint32               `protobuf:"varint,5,opt,name=dualAuthTimeout,proto3" json:"dualAuthTimeout,omitempty"`
	DualAuthApproval          DualAuthApprovalType `protobuf:"varint,6,opt,name=dualAuthApproval,proto3,enum=lift.DualAuthApprovalType" json:"dualAuthApproval,omitempty"`
	DualAuthRequiredDeviceIDs []uint32             `protobuf:"varint,7,rep,packed,name=dualAuthRequiredDeviceIDs,proto3" json:"dualAuthRequiredDeviceIDs,omitempty"`
	DualAuthScheduleID        uint32               `protobuf:"varint,8,opt,name=dualAuthScheduleID,proto3" json:"dualAuthScheduleID,omitempty"`
	Floors                    []*Floor             `protobuf:"bytes,9,rep,name=floors,proto3" json:"floors,omitempty"`
	DualAuthApprovalGroupIDs  []uint32             `protobuf:"varint,10,rep,packed,name=dualAuthApprovalGroupIDs,proto3" json:"dualAuthApprovalGroupIDs,omitempty"`
	Alarms                    []*Alarm             `protobuf:"bytes,11,rep,name=alarms,proto3" json:"alarms,omitempty"`
	AlarmFlags                uint32               `protobuf:"varint,12,opt,name=alarmFlags,proto3" json:"alarmFlags,omitempty"`
	Tamper                    *Alarm               `protobuf:"bytes,13,opt,name=tamper,proto3" json:"tamper,omitempty"`
	TamperOn                  bool                 `protobuf:"varint,14,opt,name=tamperOn,proto3" json:"tamperOn,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}             `json:"-"`
	XXX_unrecognized          []byte               `json:"-"`
	XXX_sizecache             int32                `json:"-"`
}

func (m *LiftInfo) Reset()         { *m = LiftInfo{} }
func (m *LiftInfo) String() string { return proto.CompactTextString(m) }
func (*LiftInfo) ProtoMessage()    {}
func (*LiftInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{5}
}

func (m *LiftInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiftInfo.Unmarshal(m, b)
}
func (m *LiftInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiftInfo.Marshal(b, m, deterministic)
}
func (m *LiftInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiftInfo.Merge(m, src)
}
func (m *LiftInfo) XXX_Size() int {
	return xxx_messageInfo_LiftInfo.Size(m)
}
func (m *LiftInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LiftInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LiftInfo proto.InternalMessageInfo

func (m *LiftInfo) GetLiftID() uint32 {
	if m != nil {
		return m.LiftID
	}
	return 0
}

func (m *LiftInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LiftInfo) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *LiftInfo) GetActivateTimeout() uint32 {
	if m != nil {
		return m.ActivateTimeout
	}
	return 0
}

func (m *LiftInfo) GetDualAuthTimeout() uint32 {
	if m != nil {
		return m.DualAuthTimeout
	}
	return 0
}

func (m *LiftInfo) GetDualAuthApproval() DualAuthApprovalType {
	if m != nil {
		return m.DualAuthApproval
	}
	return DualAuthApprovalType_NONE_ON_LIFT
}

func (m *LiftInfo) GetDualAuthRequiredDeviceIDs() []uint32 {
	if m != nil {
		return m.DualAuthRequiredDeviceIDs
	}
	return nil
}

func (m *LiftInfo) GetDualAuthScheduleID() uint32 {
	if m != nil {
		return m.DualAuthScheduleID
	}
	return 0
}

func (m *LiftInfo) GetFloors() []*Floor {
	if m != nil {
		return m.Floors
	}
	return nil
}

func (m *LiftInfo) GetDualAuthApprovalGroupIDs() []uint32 {
	if m != nil {
		return m.DualAuthApprovalGroupIDs
	}
	return nil
}

func (m *LiftInfo) GetAlarms() []*Alarm {
	if m != nil {
		return m.Alarms
	}
	return nil
}

func (m *LiftInfo) GetAlarmFlags() uint32 {
	if m != nil {
		return m.AlarmFlags
	}
	return 0
}

func (m *LiftInfo) GetTamper() *Alarm {
	if m != nil {
		return m.Tamper
	}
	return nil
}

func (m *LiftInfo) GetTamperOn() bool {
	if m != nil {
		return m.TamperOn
	}
	return false
}

type GetListRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{6}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetListResponse struct {
	Lifts                []*LiftInfo `protobuf:"bytes,1,rep,name=lifts,proto3" json:"lifts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{7}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetLifts() []*LiftInfo {
	if m != nil {
		return m.Lifts
	}
	return nil
}

type GetStatusRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{8}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

func (m *GetStatusRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetStatusResponse struct {
	Status               []*Status `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{9}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetStatus() []*Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type AddRequest struct {
	DeviceID             uint32      `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Lifts                []*LiftInfo `protobuf:"bytes,2,rep,name=lifts,proto3" json:"lifts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{10}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *AddRequest) GetLifts() []*LiftInfo {
	if m != nil {
		return m.Lifts
	}
	return nil
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{11}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

type DeleteRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	LiftIDs              []uint32 `protobuf:"varint,2,rep,packed,name=liftIDs,proto3" json:"liftIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{12}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *DeleteRequest) GetLiftIDs() []uint32 {
	if m != nil {
		return m.LiftIDs
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{13}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type DeleteAllRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllRequest) Reset()         { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()    {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{14}
}

func (m *DeleteAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllRequest.Unmarshal(m, b)
}
func (m *DeleteAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllRequest.Merge(m, src)
}
func (m *DeleteAllRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllRequest.Size(m)
}
func (m *DeleteAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllRequest proto.InternalMessageInfo

func (m *DeleteAllRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type DeleteAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllResponse) Reset()         { *m = DeleteAllResponse{} }
func (m *DeleteAllResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllResponse) ProtoMessage()    {}
func (*DeleteAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{15}
}

func (m *DeleteAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllResponse.Unmarshal(m, b)
}
func (m *DeleteAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllResponse.Merge(m, src)
}
func (m *DeleteAllResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllResponse.Size(m)
}
func (m *DeleteAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllResponse proto.InternalMessageInfo

type ActivateRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	LiftID               uint32   `protobuf:"varint,2,opt,name=liftID,proto3" json:"liftID,omitempty"`
	FloorIndexes         []uint32 `protobuf:"varint,3,rep,packed,name=floorIndexes,proto3" json:"floorIndexes,omitempty"`
	ActivateFlag         uint32   `protobuf:"varint,4,opt,name=activateFlag,proto3" json:"activateFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateRequest) Reset()         { *m = ActivateRequest{} }
func (m *ActivateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateRequest) ProtoMessage()    {}
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{16}
}

func (m *ActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateRequest.Unmarshal(m, b)
}
func (m *ActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateRequest.Marshal(b, m, deterministic)
}
func (m *ActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateRequest.Merge(m, src)
}
func (m *ActivateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateRequest.Size(m)
}
func (m *ActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateRequest proto.InternalMessageInfo

func (m *ActivateRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *ActivateRequest) GetLiftID() uint32 {
	if m != nil {
		return m.LiftID
	}
	return 0
}

func (m *ActivateRequest) GetFloorIndexes() []uint32 {
	if m != nil {
		return m.FloorIndexes
	}
	return nil
}

func (m *ActivateRequest) GetActivateFlag() uint32 {
	if m != nil {
		return m.ActivateFlag
	}
	return 0
}

type ActivateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateResponse) Reset()         { *m = ActivateResponse{} }
func (m *ActivateResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateResponse) ProtoMessage()    {}
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{17}
}

func (m *ActivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateResponse.Unmarshal(m, b)
}
func (m *ActivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateResponse.Marshal(b, m, deterministic)
}
func (m *ActivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateResponse.Merge(m, src)
}
func (m *ActivateResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateResponse.Size(m)
}
func (m *ActivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateResponse proto.InternalMessageInfo

type DeactivateRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	LiftID               uint32   `protobuf:"varint,2,opt,name=liftID,proto3" json:"liftID,omitempty"`
	FloorIndexes         []uint32 `protobuf:"varint,3,rep,packed,name=floorIndexes,proto3" json:"floorIndexes,omitempty"`
	DeactivateFlag       uint32   `protobuf:"varint,4,opt,name=deactivateFlag,proto3" json:"deactivateFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeactivateRequest) Reset()         { *m = DeactivateRequest{} }
func (m *DeactivateRequest) String() string { return proto.CompactTextString(m) }
func (*DeactivateRequest) ProtoMessage()    {}
func (*DeactivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{18}
}

func (m *DeactivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivateRequest.Unmarshal(m, b)
}
func (m *DeactivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivateRequest.Marshal(b, m, deterministic)
}
func (m *DeactivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivateRequest.Merge(m, src)
}
func (m *DeactivateRequest) XXX_Size() int {
	return xxx_messageInfo_DeactivateRequest.Size(m)
}
func (m *DeactivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivateRequest proto.InternalMessageInfo

func (m *DeactivateRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *DeactivateRequest) GetLiftID() uint32 {
	if m != nil {
		return m.LiftID
	}
	return 0
}

func (m *DeactivateRequest) GetFloorIndexes() []uint32 {
	if m != nil {
		return m.FloorIndexes
	}
	return nil
}

func (m *DeactivateRequest) GetDeactivateFlag() uint32 {
	if m != nil {
		return m.DeactivateFlag
	}
	return 0
}

type DeactivateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeactivateResponse) Reset()         { *m = DeactivateResponse{} }
func (m *DeactivateResponse) String() string { return proto.CompactTextString(m) }
func (*DeactivateResponse) ProtoMessage()    {}
func (*DeactivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{19}
}

func (m *DeactivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivateResponse.Unmarshal(m, b)
}
func (m *DeactivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivateResponse.Marshal(b, m, deterministic)
}
func (m *DeactivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivateResponse.Merge(m, src)
}
func (m *DeactivateResponse) XXX_Size() int {
	return xxx_messageInfo_DeactivateResponse.Size(m)
}
func (m *DeactivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivateResponse proto.InternalMessageInfo

type ReleaseRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	LiftID               uint32   `protobuf:"varint,2,opt,name=liftID,proto3" json:"liftID,omitempty"`
	FloorIndexes         []uint32 `protobuf:"varint,3,rep,packed,name=floorIndexes,proto3" json:"floorIndexes,omitempty"`
	FloorFlag            uint32   `protobuf:"varint,4,opt,name=floorFlag,proto3" json:"floorFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseRequest) Reset()         { *m = ReleaseRequest{} }
func (m *ReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*ReleaseRequest) ProtoMessage()    {}
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{20}
}

func (m *ReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseRequest.Unmarshal(m, b)
}
func (m *ReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseRequest.Marshal(b, m, deterministic)
}
func (m *ReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseRequest.Merge(m, src)
}
func (m *ReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_ReleaseRequest.Size(m)
}
func (m *ReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseRequest proto.InternalMessageInfo

func (m *ReleaseRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *ReleaseRequest) GetLiftID() uint32 {
	if m != nil {
		return m.LiftID
	}
	return 0
}

func (m *ReleaseRequest) GetFloorIndexes() []uint32 {
	if m != nil {
		return m.FloorIndexes
	}
	return nil
}

func (m *ReleaseRequest) GetFloorFlag() uint32 {
	if m != nil {
		return m.FloorFlag
	}
	return 0
}

type ReleaseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseResponse) Reset()         { *m = ReleaseResponse{} }
func (m *ReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*ReleaseResponse) ProtoMessage()    {}
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{21}
}

func (m *ReleaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseResponse.Unmarshal(m, b)
}
func (m *ReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseResponse.Marshal(b, m, deterministic)
}
func (m *ReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseResponse.Merge(m, src)
}
func (m *ReleaseResponse) XXX_Size() int {
	return xxx_messageInfo_ReleaseResponse.Size(m)
}
func (m *ReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseResponse proto.InternalMessageInfo

type SetAlarmRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	LiftIDs              []uint32 `protobuf:"varint,2,rep,packed,name=liftIDs,proto3" json:"liftIDs,omitempty"`
	AlarmFlag            uint32   `protobuf:"varint,3,opt,name=alarmFlag,proto3" json:"alarmFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmRequest) Reset()         { *m = SetAlarmRequest{} }
func (m *SetAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*SetAlarmRequest) ProtoMessage()    {}
func (*SetAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{22}
}

func (m *SetAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmRequest.Unmarshal(m, b)
}
func (m *SetAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmRequest.Marshal(b, m, deterministic)
}
func (m *SetAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmRequest.Merge(m, src)
}
func (m *SetAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_SetAlarmRequest.Size(m)
}
func (m *SetAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmRequest proto.InternalMessageInfo

func (m *SetAlarmRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetAlarmRequest) GetLiftIDs() []uint32 {
	if m != nil {
		return m.LiftIDs
	}
	return nil
}

func (m *SetAlarmRequest) GetAlarmFlag() uint32 {
	if m != nil {
		return m.AlarmFlag
	}
	return 0
}

type SetAlarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmResponse) Reset()         { *m = SetAlarmResponse{} }
func (m *SetAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*SetAlarmResponse) ProtoMessage()    {}
func (*SetAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de3e081caffb029, []int{23}
}

func (m *SetAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmResponse.Unmarshal(m, b)
}
func (m *SetAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmResponse.Marshal(b, m, deterministic)
}
func (m *SetAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmResponse.Merge(m, src)
}
func (m *SetAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_SetAlarmResponse.Size(m)
}
func (m *SetAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("lift.FloorFlag", FloorFlag_name, FloorFlag_value)
	proto.RegisterEnum("lift.AlarmFlag", AlarmFlag_name, AlarmFlag_value)
	proto.RegisterEnum("lift.DualAuthApprovalType", DualAuthApprovalType_name, DualAuthApprovalType_value)
	proto.RegisterType((*FloorStatus)(nil), "lift.FloorStatus")
	proto.RegisterType((*Floor)(nil), "lift.Floor")
	proto.RegisterType((*Sensor)(nil), "lift.Sensor")
	proto.RegisterType((*Alarm)(nil), "lift.Alarm")
	proto.RegisterType((*Status)(nil), "lift.Status")
	proto.RegisterType((*LiftInfo)(nil), "lift.LiftInfo")
	proto.RegisterType((*GetListRequest)(nil), "lift.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "lift.GetListResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "lift.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "lift.GetStatusResponse")
	proto.RegisterType((*AddRequest)(nil), "lift.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "lift.AddResponse")
	proto.RegisterType((*DeleteRequest)(nil), "lift.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "lift.DeleteResponse")
	proto.RegisterType((*DeleteAllRequest)(nil), "lift.DeleteAllRequest")
	proto.RegisterType((*DeleteAllResponse)(nil), "lift.DeleteAllResponse")
	proto.RegisterType((*ActivateRequest)(nil), "lift.ActivateRequest")
	proto.RegisterType((*ActivateResponse)(nil), "lift.ActivateResponse")
	proto.RegisterType((*DeactivateRequest)(nil), "lift.DeactivateRequest")
	proto.RegisterType((*DeactivateResponse)(nil), "lift.DeactivateResponse")
	proto.RegisterType((*ReleaseRequest)(nil), "lift.ReleaseRequest")
	proto.RegisterType((*ReleaseResponse)(nil), "lift.ReleaseResponse")
	proto.RegisterType((*SetAlarmRequest)(nil), "lift.SetAlarmRequest")
	proto.RegisterType((*SetAlarmResponse)(nil), "lift.SetAlarmResponse")
}

func init() { proto.RegisterFile("lift.proto", fileDescriptor_6de3e081caffb029) }

var fileDescriptor_6de3e081caffb029 = []byte{
	// 1097 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5b, 0x6f, 0xe3, 0x54,
	0x10, 0xae, 0x5b, 0xc7, 0x4d, 0x26, 0x97, 0x3a, 0x67, 0x43, 0xd7, 0x58, 0x2b, 0x54, 0x79, 0xab,
	0xaa, 0x54, 0x28, 0x2b, 0xb2, 0xd2, 0xa2, 0x5d, 0x55, 0x42, 0xa6, 0x71, 0x4a, 0xa4, 0x34, 0xa9,
	0x4e, 0xb2, 0x0f, 0xf0, 0x52, 0xb9, 0xf1, 0x29, 0x8d, 0x70, 0x62, 0x63, 0x3b, 0x85, 0x15, 0xef,
	0x20, 0x21, 0xf1, 0xc4, 0x2b, 0x7f, 0x87, 0xff, 0x85, 0xce, 0xcd, 0xb7, 0x6c, 0x57, 0x11, 0x08,
	0x9e, 0xe2, 0xf3, 0xcd, 0x78, 0xe6, 0x9b, 0x33, 0xdf, 0x8c, 0x03, 0xe0, 0x2f, 0xee, 0x92, 0x6e,
	0x18, 0x05, 0x49, 0x80, 0x54, 0xfa, 0x6c, 0x36, 0x3c, 0xf2, 0xb0, 0x98, 0x13, 0x8e, 0x99, 0x0d,
	0x77, 0x9e, 0x2c, 0x82, 0x15, 0x3f, 0x59, 0x3f, 0x43, 0x7d, 0xe0, 0x07, 0x41, 0x34, 0x4d, 0xdc,
	0x64, 0x1d, 0xa3, 0x67, 0x50, 0xa3, 0xe6, 0x07, 0x37, 0x21, 0x9e, 0xa1, 0x1c, 0x29, 0xa7, 0x55,
	0x9c, 0x01, 0xe8, 0x18, 0x9a, 0xf2, 0x30, 0xf0, 0xdd, 0xef, 0x62, 0x63, 0xf7, 0x48, 0x39, 0x6d,
	0xe2, 0x22, 0x88, 0x4e, 0xe1, 0xc0, 0x23, 0x45, 0xbf, 0x3d, 0xe6, 0x57, 0x86, 0xad, 0x5b, 0xa8,
	0xb0, 0xe4, 0xc8, 0x84, 0x2a, 0xe7, 0x38, 0xec, 0xb3, 0xac, 0x4d, 0x9c, 0x9e, 0x11, 0x02, 0x35,
	0x0c, 0xa2, 0x44, 0xe4, 0x62, 0xcf, 0xe8, 0x53, 0xd0, 0x62, 0x46, 0x98, 0x45, 0xae, 0xf7, 0xda,
	0x5d, 0x56, 0x74, 0xae, 0x12, 0x2c, 0x1c, 0xac, 0x3f, 0x15, 0xd0, 0xa6, 0x64, 0x15, 0xff, 0x83,
	0x2c, 0x27, 0xa0, 0x26, 0xef, 0x42, 0xc2, 0x72, 0xb4, 0x7a, 0xa8, 0x2b, 0xae, 0x71, 0xfa, 0xe3,
	0x22, 0x99, 0xdf, 0xcf, 0xde, 0x85, 0x04, 0x33, 0x3b, 0x8b, 0xbb, 0x8e, 0x5c, 0x7a, 0xab, 0x86,
	0x2a, 0xe2, 0x8a, 0x33, 0xfa, 0x04, 0x20, 0x9e, 0xdf, 0x13, 0x6f, 0xed, 0xd3, 0xac, 0x15, 0x66,
	0xcd, 0x21, 0xd6, 0x5b, 0xa8, 0xd8, 0xbe, 0x1b, 0x2d, 0xd1, 0x31, 0x68, 0x31, 0xa3, 0xc9, 0xa8,
	0xd5, 0x7b, 0x0d, 0x5e, 0x12, 0xa7, 0x8e, 0x85, 0x0d, 0x9d, 0x80, 0xc6, 0xdb, 0xc7, 0x88, 0xd6,
	0x7b, 0xad, 0xae, 0xe8, 0xa6, 0xcd, 0x7e, 0xb0, 0xb0, 0x5a, 0xbf, 0xd2, 0xaa, 0x79, 0x4b, 0x0f,
	0x41, 0xa3, 0x91, 0xd2, 0x9a, 0xc5, 0x89, 0x32, 0x73, 0x69, 0xe6, 0x7c, 0x27, 0x73, 0x08, 0xad,
	0x2a, 0x71, 0x97, 0x21, 0x89, 0x26, 0x2b, 0x76, 0x03, 0x55, 0x9c, 0x9e, 0xe9, 0xfd, 0xdf, 0xd1,
	0xbb, 0x8e, 0x0d, 0xf5, 0x68, 0xef, 0x91, 0xfb, 0xe7, 0x0e, 0xd6, 0x5f, 0x2a, 0x54, 0x47, 0x34,
	0xe3, 0xea, 0x2e, 0x78, 0x94, 0x0b, 0x02, 0x75, 0xe5, 0x2e, 0x09, 0x63, 0x51, 0xc3, 0xec, 0x99,
	0x4a, 0x51, 0x76, 0x87, 0xb6, 0x79, 0xef, 0xb4, 0x89, 0x33, 0x80, 0x8a, 0x4c, 0x6a, 0x69, 0xb6,
	0x58, 0x92, 0x60, 0x9d, 0x88, 0xab, 0x2f, 0xc3, 0x4c, 0x8e, 0x6b, 0xd7, 0xb7, 0xd7, 0xc9, 0xbd,
	0xf4, 0xac, 0x08, 0x39, 0x16, 0x61, 0x34, 0x00, 0x5d, 0x42, 0x76, 0x18, 0x46, 0xc1, 0x83, 0xeb,
	0x1b, 0x1a, 0xeb, 0xbd, 0xc9, 0xeb, 0xeb, 0x97, 0xac, 0x4c, 0x03, 0x1b, 0xef, 0xa0, 0x73, 0xf8,
	0x58, 0x62, 0x98, 0xfc, 0xb0, 0x5e, 0x44, 0xc4, 0xeb, 0xa7, 0x95, 0xec, 0xb3, 0x4a, 0x1e, 0x77,
	0x40, 0x5d, 0x40, 0xd2, 0x38, 0xcd, 0x94, 0x53, 0x65, 0x94, 0xdf, 0x63, 0x41, 0xcf, 0xd3, 0x5e,
	0xd4, 0x58, 0x2f, 0xea, 0xb9, 0x5e, 0xc8, 0x2e, 0xa0, 0x37, 0x60, 0x94, 0x69, 0x5e, 0x46, 0xc1,
	0x3a, 0xa4, 0x8c, 0x80, 0x31, 0x7a, 0xd4, 0x4e, 0x13, 0x30, 0x59, 0xc4, 0x46, 0x3d, 0x9f, 0x80,
	0xc9, 0x16, 0x0b, 0x53, 0x49, 0x4d, 0x8d, 0x0d, 0x35, 0x3d, 0x07, 0x8d, 0xab, 0xc7, 0x68, 0x32,
	0xe1, 0x16, 0x83, 0x70, 0x53, 0x41, 0x72, 0xad, 0xa2, 0xe4, 0xac, 0xcf, 0xa0, 0x75, 0x49, 0x92,
	0xd1, 0x22, 0x4e, 0xe8, 0x95, 0x91, 0x38, 0xf9, 0xd0, 0x38, 0x5b, 0x5f, 0xc0, 0x41, 0xea, 0x1d,
	0x87, 0xc1, 0x2a, 0x26, 0xe8, 0x18, 0x2a, 0x34, 0x65, 0x6c, 0x28, 0xac, 0x8a, 0x16, 0x27, 0x20,
	0xa5, 0x89, 0xb9, 0xd1, 0xea, 0x82, 0x7e, 0x49, 0x12, 0xa1, 0xe1, 0x2d, 0x12, 0xbd, 0x86, 0x76,
	0xce, 0x3f, 0x4d, 0x25, 0xd7, 0x13, 0xcf, 0x25, 0x67, 0xb9, 0xb8, 0x99, 0xc6, 0x00, 0xb6, 0xe7,
	0x6d, 0x91, 0x24, 0xa3, 0xbe, 0xfb, 0x21, 0xea, 0x4d, 0xa8, 0xb3, 0x78, 0x9c, 0x84, 0xe5, 0x40,
	0xb3, 0x4f, 0x7c, 0x92, 0x90, 0x6d, 0x32, 0x18, 0xb0, 0xcf, 0x47, 0x91, 0xe7, 0x68, 0x62, 0x79,
	0xb4, 0x74, 0x68, 0xc9, 0x30, 0x22, 0x70, 0x17, 0x74, 0x8e, 0xd8, 0xbe, 0xbf, 0xcd, 0x15, 0x3d,
	0x81, 0x76, 0xce, 0x5f, 0x04, 0xf9, 0x5d, 0x81, 0x03, 0x5b, 0x4c, 0xea, 0x36, 0x04, 0xb3, 0xcd,
	0xb1, 0x5b, 0xd8, 0x1c, 0x16, 0x34, 0x98, 0xc4, 0x87, 0x2b, 0x8f, 0xfc, 0x44, 0xe4, 0xa2, 0x28,
	0x60, 0xd4, 0x27, 0xff, 0xdd, 0x11, 0x8b, 0xa2, 0x80, 0x59, 0x08, 0xf4, 0x8c, 0x8e, 0xe0, 0xf8,
	0x87, 0x42, 0x99, 0xbb, 0xff, 0x13, 0xcb, 0x13, 0x68, 0x15, 0xbf, 0x8f, 0x82, 0x67, 0x09, 0xb5,
	0x3a, 0x80, 0xf2, 0xa4, 0x04, 0xd7, 0x5f, 0x14, 0x68, 0x61, 0xe2, 0x13, 0x37, 0xfe, 0xcf, 0x89,
	0x3e, 0x83, 0x1a, 0x3b, 0xe7, 0x38, 0x66, 0x80, 0xd5, 0x86, 0x83, 0x94, 0x87, 0xe0, 0x46, 0xe0,
	0x60, 0x4a, 0x12, 0x3e, 0xea, 0xff, 0x46, 0x8b, 0xec, 0xdf, 0x89, 0x5c, 0x29, 0xe2, 0x3f, 0x45,
	0x06, 0xd0, 0x16, 0x66, 0x69, 0x78, 0xea, 0xb3, 0x11, 0xd4, 0x06, 0x92, 0x1a, 0xaa, 0x82, 0x3a,
	0x9e, 0x8c, 0x1d, 0x7d, 0x07, 0x35, 0xa0, 0x3a, 0xbd, 0xf8, 0xda, 0xe9, 0xbf, 0x1d, 0x39, 0xba,
	0x42, 0x4f, 0x93, 0x6b, 0x07, 0xdb, 0xb3, 0x09, 0xd6, 0x55, 0x04, 0xa0, 0xd9, 0x17, 0xb3, 0xe1,
	0x64, 0xac, 0x57, 0x51, 0x13, 0x6a, 0xce, 0x95, 0x83, 0x2f, 0x9d, 0xf1, 0xc5, 0x37, 0xfa, 0xee,
	0xd9, 0x39, 0xd4, 0x6c, 0x99, 0x8e, 0xbe, 0x35, 0x9e, 0xdc, 0xd8, 0x23, 0x1b, 0x5f, 0xe9, 0x3b,
	0xa8, 0x06, 0x95, 0xc1, 0x10, 0x4f, 0x67, 0xba, 0x42, 0x03, 0x4c, 0x9d, 0x8b, 0xc9, 0xb8, 0xaf,
	0xef, 0xd2, 0xe7, 0x99, 0x7d, 0x75, 0xed, 0x60, 0x5d, 0x3d, 0x7b, 0x03, 0x9d, 0xf7, 0x7d, 0x40,
	0x90, 0x0e, 0x0d, 0x4a, 0xeb, 0x66, 0x32, 0xbe, 0x19, 0x0d, 0x07, 0x33, 0x7d, 0x87, 0x22, 0x23,
	0x7b, 0x3a, 0x4b, 0x11, 0xa5, 0xf7, 0x9b, 0x0a, 0x2a, 0x9d, 0x77, 0xf4, 0x0a, 0xf6, 0xc5, 0x62,
	0x43, 0x1d, 0xbe, 0x06, 0x8a, 0x5b, 0xd1, 0xfc, 0xa8, 0x84, 0x8a, 0x95, 0x74, 0x0e, 0xb5, 0x74,
	0x4f, 0xa1, 0xc3, 0xd4, 0xa7, 0xb0, 0xe8, 0xcc, 0xa7, 0x1b, 0xb8, 0x78, 0xfb, 0x0c, 0xf6, 0x6c,
	0xcf, 0x43, 0xba, 0x58, 0xda, 0xe9, 0xd6, 0x32, 0xdb, 0x39, 0x44, 0xf8, 0xbe, 0x04, 0x8d, 0x8f,
	0x3b, 0x7a, 0x22, 0xbe, 0x9a, 0xf9, 0x2d, 0x64, 0x76, 0x8a, 0x60, 0x46, 0x2f, 0xdd, 0x11, 0x92,
	0x5e, 0x79, 0xc9, 0x48, 0x7a, 0x1b, 0xcb, 0x04, 0xbd, 0x86, 0xaa, 0x1c, 0x5e, 0x24, 0xea, 0x2f,
	0xed, 0x16, 0xf3, 0xb0, 0x0c, 0x8b, 0x57, 0xbf, 0x04, 0xc8, 0xa6, 0x09, 0xa5, 0x19, 0x4a, 0x43,
	0x6f, 0x1a, 0x9b, 0x06, 0x11, 0xe0, 0x15, 0xec, 0x0b, 0xbd, 0xcb, 0x86, 0x14, 0xc7, 0x50, 0x36,
	0xa4, 0x34, 0x14, 0x94, 0xb3, 0x54, 0xab, 0xe4, 0x5c, 0x1a, 0x12, 0xc9, 0xb9, 0x2c, 0xea, 0xaf,
	0x3e, 0x87, 0xa7, 0xf3, 0x60, 0xd9, 0x8d, 0xd7, 0x61, 0x44, 0x96, 0xee, 0x62, 0x35, 0xef, 0xc6,
	0xde, 0xf7, 0xcc, 0xf7, 0x5a, 0xf9, 0xb6, 0x73, 0xbb, 0x08, 0xe2, 0xc4, 0x8d, 0x5e, 0xc4, 0x24,
	0xa2, 0x03, 0xf5, 0x82, 0xe2, 0xb7, 0x1a, 0xfb, 0xb7, 0xff, 0xf2, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x94, 0x97, 0xc9, 0x1d, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LiftClient is the client API for Lift service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LiftClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error)
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	Deactivate(ctx context.Context, in *DeactivateRequest, opts ...grpc.CallOption) (*DeactivateResponse, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error)
}

type liftClient struct {
	cc *grpc.ClientConn
}

func NewLiftClient(cc *grpc.ClientConn) LiftClient {
	return &liftClient{cc}
}

func (c *liftClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error) {
	out := new(DeleteAllResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/DeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/Activate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) Deactivate(ctx context.Context, in *DeactivateRequest, opts ...grpc.CallOption) (*DeactivateResponse, error) {
	out := new(DeactivateResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/Deactivate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/Release", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liftClient) SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error) {
	out := new(SetAlarmResponse)
	err := c.cc.Invoke(ctx, "/lift.Lift/SetAlarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiftServer is the server API for Lift service.
type LiftServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteAll(context.Context, *DeleteAllRequest) (*DeleteAllResponse, error)
	Activate(context.Context, *ActivateRequest) (*ActivateResponse, error)
	Deactivate(context.Context, *DeactivateRequest) (*DeactivateResponse, error)
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	SetAlarm(context.Context, *SetAlarmRequest) (*SetAlarmResponse, error)
}

func RegisterLiftServer(s *grpc.Server, srv LiftServer) {
	s.RegisterService(&_Lift_serviceDesc, srv)
}

func _Lift_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).DeleteAll(ctx, req.(*DeleteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_Deactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/Deactivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).Deactivate(ctx, req.(*DeactivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/Release",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lift_SetAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftServer).SetAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lift.Lift/SetAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftServer).SetAlarm(ctx, req.(*SetAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lift_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lift.Lift",
	HandlerType: (*LiftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _Lift_GetList_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Lift_GetStatus_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Lift_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Lift_Delete_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _Lift_DeleteAll_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _Lift_Activate_Handler,
		},
		{
			MethodName: "Deactivate",
			Handler:    _Lift_Deactivate_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _Lift_Release_Handler,
		},
		{
			MethodName: "SetAlarm",
			Handler:    _Lift_SetAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lift.proto",
}
