// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package server

import (
	card "biostar/service/card"
	finger "biostar/service/finger"
	user "biostar/service/user"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestType int32

const (
	RequestType_NO_REQUEST          RequestType = 0
	RequestType_VERIFY_REQUEST      RequestType = 1
	RequestType_IDENTIFY_REQUEST    RequestType = 2
	RequestType_GLOBAL_APB_REQUEST  RequestType = 3
	RequestType_USER_PHRASE_REQUEST RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "NO_REQUEST",
	1: "VERIFY_REQUEST",
	2: "IDENTIFY_REQUEST",
	3: "GLOBAL_APB_REQUEST",
	4: "USER_PHRASE_REQUEST",
}

var RequestType_value = map[string]int32{
	"NO_REQUEST":          0,
	"VERIFY_REQUEST":      1,
	"IDENTIFY_REQUEST":    2,
	"GLOBAL_APB_REQUEST":  3,
	"USER_PHRASE_REQUEST": 4,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

type ServerErrorCode int32

const (
	ServerErrorCode_SUCCESS            ServerErrorCode = 0
	ServerErrorCode_VERIFY_FAIL        ServerErrorCode = -301
	ServerErrorCode_IDENTIFY_FAIL      ServerErrorCode = -302
	ServerErrorCode_HARD_APB_VIOLATION ServerErrorCode = -1202
	ServerErrorCode_SOFT_APB_VIOLATION ServerErrorCode = -1203
	ServerErrorCode_CANNOT_FIND_USER   ServerErrorCode = -714
)

var ServerErrorCode_name = map[int32]string{
	0:     "SUCCESS",
	-301:  "VERIFY_FAIL",
	-302:  "IDENTIFY_FAIL",
	-1202: "HARD_APB_VIOLATION",
	-1203: "SOFT_APB_VIOLATION",
	-714:  "CANNOT_FIND_USER",
}

var ServerErrorCode_value = map[string]int32{
	"SUCCESS":            0,
	"VERIFY_FAIL":        -301,
	"IDENTIFY_FAIL":      -302,
	"HARD_APB_VIOLATION": -1202,
	"SOFT_APB_VIOLATION": -1203,
	"CANNOT_FIND_USER":   -714,
}

func (x ServerErrorCode) String() string {
	return proto.EnumName(ServerErrorCode_name, int32(x))
}

func (ServerErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

type ServerRequest struct {
	ReqType              RequestType        `protobuf:"varint,1,opt,name=reqType,proto3,enum=server.RequestType" json:"reqType,omitempty"`
	DeviceID             uint32             `protobuf:"varint,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	SeqNO                uint32             `protobuf:"varint,3,opt,name=seqNO,proto3" json:"seqNO,omitempty"`
	VerifyReq            *VerifyRequest     `protobuf:"bytes,4,opt,name=verifyReq,proto3" json:"verifyReq,omitempty"`
	IdentifyReq          *IdentifyRequest   `protobuf:"bytes,5,opt,name=identifyReq,proto3" json:"identifyReq,omitempty"`
	GlobalAPBReq         *GlobalAPBRequest  `protobuf:"bytes,6,opt,name=globalAPBReq,proto3" json:"globalAPBReq,omitempty"`
	UserPhraseReq        *UserPhraseRequest `protobuf:"bytes,7,opt,name=userPhraseReq,proto3" json:"userPhraseReq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ServerRequest) Reset()         { *m = ServerRequest{} }
func (m *ServerRequest) String() string { return proto.CompactTextString(m) }
func (*ServerRequest) ProtoMessage()    {}
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *ServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerRequest.Unmarshal(m, b)
}
func (m *ServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerRequest.Marshal(b, m, deterministic)
}
func (m *ServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerRequest.Merge(m, src)
}
func (m *ServerRequest) XXX_Size() int {
	return xxx_messageInfo_ServerRequest.Size(m)
}
func (m *ServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerRequest proto.InternalMessageInfo

func (m *ServerRequest) GetReqType() RequestType {
	if m != nil {
		return m.ReqType
	}
	return RequestType_NO_REQUEST
}

func (m *ServerRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *ServerRequest) GetSeqNO() uint32 {
	if m != nil {
		return m.SeqNO
	}
	return 0
}

func (m *ServerRequest) GetVerifyReq() *VerifyRequest {
	if m != nil {
		return m.VerifyReq
	}
	return nil
}

func (m *ServerRequest) GetIdentifyReq() *IdentifyRequest {
	if m != nil {
		return m.IdentifyReq
	}
	return nil
}

func (m *ServerRequest) GetGlobalAPBReq() *GlobalAPBRequest {
	if m != nil {
		return m.GlobalAPBReq
	}
	return nil
}

func (m *ServerRequest) GetUserPhraseReq() *UserPhraseRequest {
	if m != nil {
		return m.UserPhraseReq
	}
	return nil
}

type VerifyRequest struct {
	IsCard               bool      `protobuf:"varint,1,opt,name=isCard,proto3" json:"isCard,omitempty"`
	CardType             card.Type `protobuf:"varint,2,opt,name=cardType,proto3,enum=card.Type" json:"cardType,omitempty"`
	CardData             []byte    `protobuf:"bytes,3,opt,name=cardData,proto3" json:"cardData,omitempty"`
	UserID               string    `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetIsCard() bool {
	if m != nil {
		return m.IsCard
	}
	return false
}

func (m *VerifyRequest) GetCardType() card.Type {
	if m != nil {
		return m.CardType
	}
	return card.Type_CARD_TYPE_UNKNOWN
}

func (m *VerifyRequest) GetCardData() []byte {
	if m != nil {
		return m.CardData
	}
	return nil
}

func (m *VerifyRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type IdentifyRequest struct {
	TemplateFormat       finger.TemplateFormat `protobuf:"varint,1,opt,name=templateFormat,proto3,enum=finger.TemplateFormat" json:"templateFormat,omitempty"`
	TemplateData         []byte                `protobuf:"bytes,2,opt,name=templateData,proto3" json:"templateData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IdentifyRequest) Reset()         { *m = IdentifyRequest{} }
func (m *IdentifyRequest) String() string { return proto.CompactTextString(m) }
func (*IdentifyRequest) ProtoMessage()    {}
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *IdentifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentifyRequest.Unmarshal(m, b)
}
func (m *IdentifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentifyRequest.Marshal(b, m, deterministic)
}
func (m *IdentifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentifyRequest.Merge(m, src)
}
func (m *IdentifyRequest) XXX_Size() int {
	return xxx_messageInfo_IdentifyRequest.Size(m)
}
func (m *IdentifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdentifyRequest proto.InternalMessageInfo

func (m *IdentifyRequest) GetTemplateFormat() finger.TemplateFormat {
	if m != nil {
		return m.TemplateFormat
	}
	return finger.TemplateFormat_TEMPLATE_FORMAT_SUPREMA
}

func (m *IdentifyRequest) GetTemplateData() []byte {
	if m != nil {
		return m.TemplateData
	}
	return nil
}

type GlobalAPBRequest struct {
	UserIDs              []string `protobuf:"bytes,1,rep,name=userIDs,proto3" json:"userIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalAPBRequest) Reset()         { *m = GlobalAPBRequest{} }
func (m *GlobalAPBRequest) String() string { return proto.CompactTextString(m) }
func (*GlobalAPBRequest) ProtoMessage()    {}
func (*GlobalAPBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *GlobalAPBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalAPBRequest.Unmarshal(m, b)
}
func (m *GlobalAPBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalAPBRequest.Marshal(b, m, deterministic)
}
func (m *GlobalAPBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalAPBRequest.Merge(m, src)
}
func (m *GlobalAPBRequest) XXX_Size() int {
	return xxx_messageInfo_GlobalAPBRequest.Size(m)
}
func (m *GlobalAPBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalAPBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalAPBRequest proto.InternalMessageInfo

func (m *GlobalAPBRequest) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type UserPhraseRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPhraseRequest) Reset()         { *m = UserPhraseRequest{} }
func (m *UserPhraseRequest) String() string { return proto.CompactTextString(m) }
func (*UserPhraseRequest) ProtoMessage()    {}
func (*UserPhraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *UserPhraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPhraseRequest.Unmarshal(m, b)
}
func (m *UserPhraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPhraseRequest.Marshal(b, m, deterministic)
}
func (m *UserPhraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPhraseRequest.Merge(m, src)
}
func (m *UserPhraseRequest) XXX_Size() int {
	return xxx_messageInfo_UserPhraseRequest.Size(m)
}
func (m *UserPhraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPhraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserPhraseRequest proto.InternalMessageInfo

func (m *UserPhraseRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type SubscribeRequest struct {
	QueueSize            int32    `protobuf:"varint,1,opt,name=queueSize,proto3" json:"queueSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetQueueSize() int32 {
	if m != nil {
		return m.QueueSize
	}
	return 0
}

type UnsubscribeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

type UnsubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeResponse) Reset()         { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()    {}
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *UnsubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeResponse.Unmarshal(m, b)
}
func (m *UnsubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeResponse.Marshal(b, m, deterministic)
}
func (m *UnsubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeResponse.Merge(m, src)
}
func (m *UnsubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeResponse.Size(m)
}
func (m *UnsubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeResponse proto.InternalMessageInfo

type HandleVerifyRequest struct {
	DeviceID             uint32          `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	SeqNO                uint32          `protobuf:"varint,2,opt,name=seqNO,proto3" json:"seqNO,omitempty"`
	ErrCode              ServerErrorCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=server.ServerErrorCode" json:"errCode,omitempty"`
	User                 *user.UserInfo  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HandleVerifyRequest) Reset()         { *m = HandleVerifyRequest{} }
func (m *HandleVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*HandleVerifyRequest) ProtoMessage()    {}
func (*HandleVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *HandleVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleVerifyRequest.Unmarshal(m, b)
}
func (m *HandleVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleVerifyRequest.Marshal(b, m, deterministic)
}
func (m *HandleVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleVerifyRequest.Merge(m, src)
}
func (m *HandleVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_HandleVerifyRequest.Size(m)
}
func (m *HandleVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleVerifyRequest proto.InternalMessageInfo

func (m *HandleVerifyRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *HandleVerifyRequest) GetSeqNO() uint32 {
	if m != nil {
		return m.SeqNO
	}
	return 0
}

func (m *HandleVerifyRequest) GetErrCode() ServerErrorCode {
	if m != nil {
		return m.ErrCode
	}
	return ServerErrorCode_SUCCESS
}

func (m *HandleVerifyRequest) GetUser() *user.UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type HandleVerifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleVerifyResponse) Reset()         { *m = HandleVerifyResponse{} }
func (m *HandleVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*HandleVerifyResponse) ProtoMessage()    {}
func (*HandleVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *HandleVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleVerifyResponse.Unmarshal(m, b)
}
func (m *HandleVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleVerifyResponse.Marshal(b, m, deterministic)
}
func (m *HandleVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleVerifyResponse.Merge(m, src)
}
func (m *HandleVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_HandleVerifyResponse.Size(m)
}
func (m *HandleVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleVerifyResponse proto.InternalMessageInfo

type HandleIdentifyRequest struct {
	DeviceID             uint32          `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	SeqNO                uint32          `protobuf:"varint,2,opt,name=seqNO,proto3" json:"seqNO,omitempty"`
	ErrCode              ServerErrorCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=server.ServerErrorCode" json:"errCode,omitempty"`
	User                 *user.UserInfo  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HandleIdentifyRequest) Reset()         { *m = HandleIdentifyRequest{} }
func (m *HandleIdentifyRequest) String() string { return proto.CompactTextString(m) }
func (*HandleIdentifyRequest) ProtoMessage()    {}
func (*HandleIdentifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{10}
}

func (m *HandleIdentifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleIdentifyRequest.Unmarshal(m, b)
}
func (m *HandleIdentifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleIdentifyRequest.Marshal(b, m, deterministic)
}
func (m *HandleIdentifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleIdentifyRequest.Merge(m, src)
}
func (m *HandleIdentifyRequest) XXX_Size() int {
	return xxx_messageInfo_HandleIdentifyRequest.Size(m)
}
func (m *HandleIdentifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleIdentifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleIdentifyRequest proto.InternalMessageInfo

func (m *HandleIdentifyRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *HandleIdentifyRequest) GetSeqNO() uint32 {
	if m != nil {
		return m.SeqNO
	}
	return 0
}

func (m *HandleIdentifyRequest) GetErrCode() ServerErrorCode {
	if m != nil {
		return m.ErrCode
	}
	return ServerErrorCode_SUCCESS
}

func (m *HandleIdentifyRequest) GetUser() *user.UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type HandleIdentifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleIdentifyResponse) Reset()         { *m = HandleIdentifyResponse{} }
func (m *HandleIdentifyResponse) String() string { return proto.CompactTextString(m) }
func (*HandleIdentifyResponse) ProtoMessage()    {}
func (*HandleIdentifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{11}
}

func (m *HandleIdentifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleIdentifyResponse.Unmarshal(m, b)
}
func (m *HandleIdentifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleIdentifyResponse.Marshal(b, m, deterministic)
}
func (m *HandleIdentifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleIdentifyResponse.Merge(m, src)
}
func (m *HandleIdentifyResponse) XXX_Size() int {
	return xxx_messageInfo_HandleIdentifyResponse.Size(m)
}
func (m *HandleIdentifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleIdentifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleIdentifyResponse proto.InternalMessageInfo

type HandleGlobalAPBRequest struct {
	DeviceID             uint32          `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	SeqNO                uint32          `protobuf:"varint,2,opt,name=seqNO,proto3" json:"seqNO,omitempty"`
	ErrCode              ServerErrorCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=server.ServerErrorCode" json:"errCode,omitempty"`
	ZoneID               uint32          `protobuf:"varint,4,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HandleGlobalAPBRequest) Reset()         { *m = HandleGlobalAPBRequest{} }
func (m *HandleGlobalAPBRequest) String() string { return proto.CompactTextString(m) }
func (*HandleGlobalAPBRequest) ProtoMessage()    {}
func (*HandleGlobalAPBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{12}
}

func (m *HandleGlobalAPBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleGlobalAPBRequest.Unmarshal(m, b)
}
func (m *HandleGlobalAPBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleGlobalAPBRequest.Marshal(b, m, deterministic)
}
func (m *HandleGlobalAPBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleGlobalAPBRequest.Merge(m, src)
}
func (m *HandleGlobalAPBRequest) XXX_Size() int {
	return xxx_messageInfo_HandleGlobalAPBRequest.Size(m)
}
func (m *HandleGlobalAPBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleGlobalAPBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleGlobalAPBRequest proto.InternalMessageInfo

func (m *HandleGlobalAPBRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *HandleGlobalAPBRequest) GetSeqNO() uint32 {
	if m != nil {
		return m.SeqNO
	}
	return 0
}

func (m *HandleGlobalAPBRequest) GetErrCode() ServerErrorCode {
	if m != nil {
		return m.ErrCode
	}
	return ServerErrorCode_SUCCESS
}

func (m *HandleGlobalAPBRequest) GetZoneID() uint32 {
	if m != nil {
		return m.ZoneID
	}
	return 0
}

type HandleGlobalAPBResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleGlobalAPBResponse) Reset()         { *m = HandleGlobalAPBResponse{} }
func (m *HandleGlobalAPBResponse) String() string { return proto.CompactTextString(m) }
func (*HandleGlobalAPBResponse) ProtoMessage()    {}
func (*HandleGlobalAPBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{13}
}

func (m *HandleGlobalAPBResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleGlobalAPBResponse.Unmarshal(m, b)
}
func (m *HandleGlobalAPBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleGlobalAPBResponse.Marshal(b, m, deterministic)
}
func (m *HandleGlobalAPBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleGlobalAPBResponse.Merge(m, src)
}
func (m *HandleGlobalAPBResponse) XXX_Size() int {
	return xxx_messageInfo_HandleGlobalAPBResponse.Size(m)
}
func (m *HandleGlobalAPBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleGlobalAPBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleGlobalAPBResponse proto.InternalMessageInfo

type HandleUserPhraseRequest struct {
	DeviceID             uint32          `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	SeqNO                uint32          `protobuf:"varint,2,opt,name=seqNO,proto3" json:"seqNO,omitempty"`
	ErrCode              ServerErrorCode `protobuf:"varint,3,opt,name=errCode,proto3,enum=server.ServerErrorCode" json:"errCode,omitempty"`
	UserPhrase           string          `protobuf:"bytes,4,opt,name=userPhrase,proto3" json:"userPhrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HandleUserPhraseRequest) Reset()         { *m = HandleUserPhraseRequest{} }
func (m *HandleUserPhraseRequest) String() string { return proto.CompactTextString(m) }
func (*HandleUserPhraseRequest) ProtoMessage()    {}
func (*HandleUserPhraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{14}
}

func (m *HandleUserPhraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleUserPhraseRequest.Unmarshal(m, b)
}
func (m *HandleUserPhraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleUserPhraseRequest.Marshal(b, m, deterministic)
}
func (m *HandleUserPhraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleUserPhraseRequest.Merge(m, src)
}
func (m *HandleUserPhraseRequest) XXX_Size() int {
	return xxx_messageInfo_HandleUserPhraseRequest.Size(m)
}
func (m *HandleUserPhraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleUserPhraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleUserPhraseRequest proto.InternalMessageInfo

func (m *HandleUserPhraseRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *HandleUserPhraseRequest) GetSeqNO() uint32 {
	if m != nil {
		return m.SeqNO
	}
	return 0
}

func (m *HandleUserPhraseRequest) GetErrCode() ServerErrorCode {
	if m != nil {
		return m.ErrCode
	}
	return ServerErrorCode_SUCCESS
}

func (m *HandleUserPhraseRequest) GetUserPhrase() string {
	if m != nil {
		return m.UserPhrase
	}
	return ""
}

type HandleUserPhraseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleUserPhraseResponse) Reset()         { *m = HandleUserPhraseResponse{} }
func (m *HandleUserPhraseResponse) String() string { return proto.CompactTextString(m) }
func (*HandleUserPhraseResponse) ProtoMessage()    {}
func (*HandleUserPhraseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{15}
}

func (m *HandleUserPhraseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleUserPhraseResponse.Unmarshal(m, b)
}
func (m *HandleUserPhraseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleUserPhraseResponse.Marshal(b, m, deterministic)
}
func (m *HandleUserPhraseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleUserPhraseResponse.Merge(m, src)
}
func (m *HandleUserPhraseResponse) XXX_Size() int {
	return xxx_messageInfo_HandleUserPhraseResponse.Size(m)
}
func (m *HandleUserPhraseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleUserPhraseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleUserPhraseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("server.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("server.ServerErrorCode", ServerErrorCode_name, ServerErrorCode_value)
	proto.RegisterType((*ServerRequest)(nil), "server.ServerRequest")
	proto.RegisterType((*VerifyRequest)(nil), "server.VerifyRequest")
	proto.RegisterType((*IdentifyRequest)(nil), "server.IdentifyRequest")
	proto.RegisterType((*GlobalAPBRequest)(nil), "server.GlobalAPBRequest")
	proto.RegisterType((*UserPhraseRequest)(nil), "server.UserPhraseRequest")
	proto.RegisterType((*SubscribeRequest)(nil), "server.SubscribeRequest")
	proto.RegisterType((*UnsubscribeRequest)(nil), "server.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeResponse)(nil), "server.UnsubscribeResponse")
	proto.RegisterType((*HandleVerifyRequest)(nil), "server.HandleVerifyRequest")
	proto.RegisterType((*HandleVerifyResponse)(nil), "server.HandleVerifyResponse")
	proto.RegisterType((*HandleIdentifyRequest)(nil), "server.HandleIdentifyRequest")
	proto.RegisterType((*HandleIdentifyResponse)(nil), "server.HandleIdentifyResponse")
	proto.RegisterType((*HandleGlobalAPBRequest)(nil), "server.HandleGlobalAPBRequest")
	proto.RegisterType((*HandleGlobalAPBResponse)(nil), "server.HandleGlobalAPBResponse")
	proto.RegisterType((*HandleUserPhraseRequest)(nil), "server.HandleUserPhraseRequest")
	proto.RegisterType((*HandleUserPhraseResponse)(nil), "server.HandleUserPhraseResponse")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 903 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x6e, 0x23, 0x45,
	0x14, 0x9d, 0x72, 0x12, 0x3b, 0xbe, 0x7e, 0xa4, 0xb9, 0x49, 0x9c, 0x4e, 0x33, 0x0f, 0xab, 0x17,
	0x28, 0x1a, 0xc0, 0x33, 0x64, 0xc4, 0x02, 0x09, 0x0d, 0x72, 0xfc, 0x98, 0xb4, 0x14, 0xd9, 0xa6,
	0xda, 0x8e, 0x04, 0x1b, 0xab, 0x6d, 0x57, 0x86, 0x16, 0x89, 0xdb, 0xae, 0x6e, 0x47, 0xcc, 0x6c,
	0xf9, 0x06, 0xb6, 0x88, 0x9f, 0x80, 0xbf, 0x80, 0x05, 0x2c, 0x58, 0xf2, 0x17, 0x2c, 0x90, 0x10,
	0xa8, 0xab, 0xab, 0x9f, 0x8e, 0xb7, 0xd1, 0x64, 0xe5, 0xba, 0xe7, 0x9c, 0xaa, 0x53, 0xb7, 0xee,
	0xbd, 0x1d, 0x28, 0xbb, 0x8c, 0xdf, 0x32, 0xde, 0x58, 0x70, 0xc7, 0x73, 0x30, 0x1f, 0xac, 0x34,
	0x98, 0x5a, 0x7c, 0x16, 0xc4, 0xb4, 0xf2, 0x95, 0x3d, 0x7f, 0x1d, 0x32, 0x34, 0x58, 0xb9, 0xe1,
	0x6f, 0xfd, 0xaf, 0x1c, 0x54, 0x4c, 0x21, 0xa0, 0x6c, 0xb9, 0x62, 0xae, 0x87, 0x1f, 0x43, 0x81,
	0xb3, 0xe5, 0xf0, 0xcd, 0x82, 0xa9, 0xa4, 0x4e, 0x4e, 0xaa, 0xa7, 0xfb, 0x0d, 0xb9, 0xbf, 0x64,
	0xf8, 0x10, 0x0d, 0x39, 0xa8, 0xc1, 0xee, 0x8c, 0xdd, 0xda, 0x53, 0x66, 0xb4, 0xd5, 0x5c, 0x9d,
	0x9c, 0x54, 0x68, 0xb4, 0xc6, 0x03, 0xd8, 0x71, 0xd9, 0xb2, 0xd7, 0x57, 0xb7, 0x04, 0x10, 0x2c,
	0xf0, 0x05, 0x14, 0x6f, 0x19, 0xb7, 0xaf, 0xde, 0x50, 0xb6, 0x54, 0xb7, 0xeb, 0xe4, 0xa4, 0x74,
	0x7a, 0x18, 0x1e, 0x71, 0x19, 0x02, 0xfe, 0x41, 0x34, 0xe6, 0xe1, 0x67, 0x50, 0xb2, 0x67, 0x6c,
	0xee, 0x49, 0xd9, 0x8e, 0x90, 0x1d, 0x85, 0x32, 0x23, 0x86, 0x84, 0x30, 0xc9, 0xc5, 0xcf, 0xa1,
	0xfc, 0xfa, 0xda, 0x99, 0x58, 0xd7, 0xcd, 0xc1, 0x99, 0xaf, 0xcd, 0x0b, 0xad, 0x1a, 0x6a, 0x5f,
	0x25, 0x30, 0x21, 0x4e, 0xb1, 0xf1, 0x0b, 0xa8, 0xf8, 0xe9, 0x1a, 0x7c, 0xc3, 0x2d, 0x97, 0xf9,
	0xf2, 0x82, 0x90, 0x1f, 0x87, 0xf2, 0x51, 0x12, 0x14, 0xfa, 0x34, 0x5f, 0xff, 0x9e, 0x40, 0x25,
	0x75, 0x2d, 0xac, 0x41, 0xde, 0x76, 0x5b, 0x16, 0x9f, 0x89, 0x04, 0xef, 0x52, 0xb9, 0xc2, 0x0f,
	0x60, 0xd7, 0x7f, 0x33, 0x91, 0xfa, 0x9c, 0x48, 0x3d, 0x34, 0xc4, 0x23, 0x8a, 0x8c, 0x47, 0x98,
	0x9f, 0x72, 0xff, 0x77, 0xdb, 0xf2, 0x2c, 0x91, 0xd9, 0x32, 0x8d, 0xd6, 0xfe, 0xde, 0xfe, 0xf1,
	0x46, 0x5b, 0x64, 0xb6, 0x48, 0xe5, 0x4a, 0x5f, 0xc1, 0x5e, 0x26, 0x49, 0xf8, 0x12, 0xaa, 0x1e,
	0xbb, 0x59, 0x5c, 0x5b, 0x1e, 0xeb, 0x3a, 0xfc, 0xc6, 0xf2, 0xe4, 0x7b, 0xd7, 0x1a, 0xb2, 0x5a,
	0x86, 0x29, 0x94, 0x66, 0xd8, 0xa8, 0x43, 0x39, 0x8c, 0x08, 0x2b, 0x39, 0x61, 0x25, 0x15, 0xd3,
	0x3f, 0x02, 0x25, 0x9b, 0x5f, 0x54, 0xa1, 0x10, 0x98, 0x72, 0x55, 0x52, 0xdf, 0x3a, 0x29, 0xd2,
	0x70, 0xa9, 0x7f, 0x08, 0xef, 0xad, 0xa5, 0x33, 0x71, 0x23, 0x92, 0xba, 0xd1, 0x73, 0x50, 0xcc,
	0xd5, 0xc4, 0x9d, 0x72, 0x7b, 0x12, 0x71, 0x1f, 0x42, 0x71, 0xb9, 0x62, 0x2b, 0x66, 0xda, 0x6f,
	0x83, 0xea, 0xdd, 0xa1, 0x71, 0x40, 0x3f, 0x00, 0x1c, 0xcd, 0xdd, 0x8c, 0x46, 0x3f, 0x84, 0xfd,
	0x54, 0xd4, 0x5d, 0x38, 0x73, 0x97, 0xe9, 0x3f, 0x12, 0xd8, 0x3f, 0xb7, 0xe6, 0xb3, 0x6b, 0x96,
	0x7e, 0xbc, 0x64, 0xbd, 0x93, 0x4d, 0xf5, 0x9e, 0x4b, 0xd6, 0xfb, 0x27, 0x50, 0x60, 0x9c, 0xb7,
	0x9c, 0x19, 0x13, 0xaf, 0x55, 0x8d, 0xcb, 0x36, 0x68, 0xbc, 0x0e, 0xe7, 0x8e, 0x80, 0x69, 0xc8,
	0x43, 0x1d, 0xb6, 0xfd, 0x5b, 0xca, 0xee, 0xa8, 0x36, 0x44, 0xc3, 0xfa, 0xa9, 0x31, 0xe6, 0x57,
	0x0e, 0x15, 0x98, 0x5e, 0x83, 0x83, 0xb4, 0x3f, 0x69, 0xfc, 0x27, 0x02, 0x87, 0x01, 0x90, 0x7d,
	0xf0, 0x77, 0xc6, 0xba, 0x0a, 0xb5, 0xac, 0x43, 0x69, 0xfe, 0x07, 0x12, 0x42, 0x6b, 0x65, 0x73,
	0x2f, 0xee, 0x6b, 0x90, 0x7f, 0xeb, 0xcc, 0x99, 0x6c, 0x9f, 0x0a, 0x95, 0x2b, 0xfd, 0x18, 0x8e,
	0xd6, 0x6c, 0xc5, 0x85, 0x22, 0xb1, 0xf5, 0xda, 0xbd, 0x17, 0xcf, 0x8f, 0x01, 0xe2, 0x89, 0x23,
	0xdb, 0x3e, 0x11, 0xd1, 0x35, 0x50, 0xd7, 0xfd, 0x05, 0xe6, 0x9f, 0x7e, 0x07, 0xa5, 0xc4, 0x54,
	0xc7, 0x2a, 0x40, 0xaf, 0x3f, 0xa6, 0x9d, 0x2f, 0x47, 0x1d, 0x73, 0xa8, 0x3c, 0x40, 0x84, 0xea,
	0x65, 0x87, 0x1a, 0xdd, 0xaf, 0xa2, 0x18, 0xc1, 0x03, 0x50, 0x8c, 0x76, 0xa7, 0x37, 0x4c, 0x46,
	0x73, 0x58, 0x03, 0x7c, 0x75, 0xd1, 0x3f, 0x6b, 0x5e, 0x8c, 0x9b, 0x83, 0xb3, 0x28, 0xbe, 0x85,
	0x47, 0xb0, 0x3f, 0x32, 0x3b, 0x74, 0x3c, 0x38, 0xa7, 0x4d, 0xb3, 0x13, 0x01, 0xdb, 0x4f, 0x7f,
	0x26, 0xb0, 0x97, 0xb9, 0x12, 0x96, 0xa0, 0x60, 0x8e, 0x5a, 0xad, 0x8e, 0x69, 0x2a, 0x0f, 0x50,
	0x85, 0x92, 0x3c, 0xbb, 0xdb, 0x34, 0x2e, 0x94, 0x3f, 0xfe, 0xfd, 0x2f, 0xf8, 0x23, 0xa8, 0x41,
	0x25, 0x72, 0x20, 0xb0, 0xdf, 0x63, 0xec, 0x09, 0xe0, 0x79, 0x93, 0xb6, 0x85, 0x8b, 0x4b, 0xa3,
	0x7f, 0xd1, 0x1c, 0x1a, 0xfd, 0x9e, 0xf2, 0xdb, 0xdf, 0x49, 0x82, 0xd9, 0xef, 0x0e, 0x33, 0x84,
	0x5f, 0x63, 0xc2, 0x23, 0x50, 0x5a, 0xcd, 0x5e, 0xaf, 0x3f, 0x1c, 0x77, 0x8d, 0x5e, 0x7b, 0xec,
	0xbb, 0x57, 0x7e, 0xf9, 0x27, 0x84, 0x4f, 0xff, 0xdc, 0x82, 0x7c, 0xe0, 0x1b, 0x5f, 0x42, 0x31,
	0x9a, 0x40, 0x18, 0x7d, 0x4f, 0xb2, 0x43, 0x49, 0x3b, 0x4c, 0xbf, 0xa0, 0x0c, 0x3f, 0x27, 0xd8,
	0x85, 0x52, 0x62, 0xf2, 0xa0, 0x16, 0x7d, 0x52, 0xd6, 0x86, 0x94, 0xf6, 0xfe, 0x9d, 0x58, 0xf0,
	0x88, 0x68, 0x40, 0x39, 0x39, 0x09, 0x30, 0x22, 0xdf, 0x31, 0xbf, 0xb4, 0x87, 0x77, 0x83, 0x72,
	0xab, 0x3e, 0x54, 0xd3, 0x9d, 0x89, 0x8f, 0xd2, 0xfc, 0xcc, 0x4c, 0xd1, 0x1e, 0x6f, 0x82, 0xe5,
	0x86, 0x14, 0xf6, 0x32, 0x8d, 0x83, 0x19, 0x49, 0xb6, 0xd1, 0xb5, 0x27, 0x1b, 0x71, 0xb9, 0xe7,
	0x08, 0x94, 0x6c, 0x41, 0x63, 0x46, 0xb4, 0xd6, 0x8a, 0x5a, 0x7d, 0x33, 0x21, 0xd8, 0xf6, 0xec,
	0x53, 0x38, 0x9e, 0x3a, 0x37, 0x0d, 0x77, 0xb5, 0xe0, 0xec, 0xc6, 0xb2, 0xe7, 0xd3, 0x86, 0x3b,
	0xfb, 0x56, 0xaa, 0x06, 0xe4, 0xeb, 0xda, 0xc4, 0x76, 0x5c, 0xcf, 0xe2, 0xcf, 0xfc, 0x88, 0x3d,
	0x65, 0xcf, 0x02, 0x64, 0x92, 0x17, 0xff, 0x48, 0xbd, 0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xe4,
	0xb9, 0x1f, 0xbd, 0x86, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Server_SubscribeClient, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	HandleVerify(ctx context.Context, in *HandleVerifyRequest, opts ...grpc.CallOption) (*HandleVerifyResponse, error)
	HandleIdentify(ctx context.Context, in *HandleIdentifyRequest, opts ...grpc.CallOption) (*HandleIdentifyResponse, error)
	HandleGlobalAPB(ctx context.Context, in *HandleGlobalAPBRequest, opts ...grpc.CallOption) (*HandleGlobalAPBResponse, error)
	HandleUserPhrase(ctx context.Context, in *HandleUserPhraseRequest, opts ...grpc.CallOption) (*HandleUserPhraseResponse, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Server_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Server_serviceDesc.Streams[0], "/server.Server/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Server_SubscribeClient interface {
	Recv() (*ServerRequest, error)
	grpc.ClientStream
}

type serverSubscribeClient struct {
	grpc.ClientStream
}

func (x *serverSubscribeClient) Recv() (*ServerRequest, error) {
	m := new(ServerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, "/server.Server/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) HandleVerify(ctx context.Context, in *HandleVerifyRequest, opts ...grpc.CallOption) (*HandleVerifyResponse, error) {
	out := new(HandleVerifyResponse)
	err := c.cc.Invoke(ctx, "/server.Server/HandleVerify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) HandleIdentify(ctx context.Context, in *HandleIdentifyRequest, opts ...grpc.CallOption) (*HandleIdentifyResponse, error) {
	out := new(HandleIdentifyResponse)
	err := c.cc.Invoke(ctx, "/server.Server/HandleIdentify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) HandleGlobalAPB(ctx context.Context, in *HandleGlobalAPBRequest, opts ...grpc.CallOption) (*HandleGlobalAPBResponse, error) {
	out := new(HandleGlobalAPBResponse)
	err := c.cc.Invoke(ctx, "/server.Server/HandleGlobalAPB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) HandleUserPhrase(ctx context.Context, in *HandleUserPhraseRequest, opts ...grpc.CallOption) (*HandleUserPhraseResponse, error) {
	out := new(HandleUserPhraseResponse)
	err := c.cc.Invoke(ctx, "/server.Server/HandleUserPhrase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	Subscribe(*SubscribeRequest, Server_SubscribeServer) error
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	HandleVerify(context.Context, *HandleVerifyRequest) (*HandleVerifyResponse, error)
	HandleIdentify(context.Context, *HandleIdentifyRequest) (*HandleIdentifyResponse, error)
	HandleGlobalAPB(context.Context, *HandleGlobalAPBRequest) (*HandleGlobalAPBResponse, error)
	HandleUserPhrase(context.Context, *HandleUserPhraseRequest) (*HandleUserPhraseResponse, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerServer).Subscribe(m, &serverSubscribeServer{stream})
}

type Server_SubscribeServer interface {
	Send(*ServerRequest) error
	grpc.ServerStream
}

type serverSubscribeServer struct {
	grpc.ServerStream
}

func (x *serverSubscribeServer) Send(m *ServerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Server_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Server/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_HandleVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).HandleVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Server/HandleVerify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).HandleVerify(ctx, req.(*HandleVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_HandleIdentify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleIdentifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).HandleIdentify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Server/HandleIdentify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).HandleIdentify(ctx, req.(*HandleIdentifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_HandleGlobalAPB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGlobalAPBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).HandleGlobalAPB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Server/HandleGlobalAPB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).HandleGlobalAPB(ctx, req.(*HandleGlobalAPBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_HandleUserPhrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleUserPhraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).HandleUserPhrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Server/HandleUserPhrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).HandleUserPhrase(ctx, req.(*HandleUserPhraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unsubscribe",
			Handler:    _Server_Unsubscribe_Handler,
		},
		{
			MethodName: "HandleVerify",
			Handler:    _Server_HandleVerify_Handler,
		},
		{
			MethodName: "HandleIdentify",
			Handler:    _Server_HandleIdentify_Handler,
		},
		{
			MethodName: "HandleGlobalAPB",
			Handler:    _Server_HandleGlobalAPB_Handler,
		},
		{
			MethodName: "HandleUserPhrase",
			Handler:    _Server_HandleUserPhrase_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Server_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server.proto",
}
