// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operator.proto

package operator

import (
	auth "biostar/service/auth"
	err "biostar/service/err"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{0}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetListResponse struct {
	Operators            []*auth.Operator `protobuf:"bytes,1,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{1}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetOperators() []*auth.Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

type AddRequest struct {
	DeviceID             uint32           `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Operators            []*auth.Operator `protobuf:"bytes,2,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{2}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *AddRequest) GetOperators() []*auth.Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{3}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

type AddMultiRequest struct {
	DeviceIDs            []uint32         `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	Operators            []*auth.Operator `protobuf:"bytes,2,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddMultiRequest) Reset()         { *m = AddMultiRequest{} }
func (m *AddMultiRequest) String() string { return proto.CompactTextString(m) }
func (*AddMultiRequest) ProtoMessage()    {}
func (*AddMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{4}
}

func (m *AddMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMultiRequest.Unmarshal(m, b)
}
func (m *AddMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMultiRequest.Marshal(b, m, deterministic)
}
func (m *AddMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMultiRequest.Merge(m, src)
}
func (m *AddMultiRequest) XXX_Size() int {
	return xxx_messageInfo_AddMultiRequest.Size(m)
}
func (m *AddMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMultiRequest proto.InternalMessageInfo

func (m *AddMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *AddMultiRequest) GetOperators() []*auth.Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

type AddMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddMultiResponse) Reset()         { *m = AddMultiResponse{} }
func (m *AddMultiResponse) String() string { return proto.CompactTextString(m) }
func (*AddMultiResponse) ProtoMessage()    {}
func (*AddMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{5}
}

func (m *AddMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMultiResponse.Unmarshal(m, b)
}
func (m *AddMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMultiResponse.Marshal(b, m, deterministic)
}
func (m *AddMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMultiResponse.Merge(m, src)
}
func (m *AddMultiResponse) XXX_Size() int {
	return xxx_messageInfo_AddMultiResponse.Size(m)
}
func (m *AddMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMultiResponse proto.InternalMessageInfo

func (m *AddMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type DeleteRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	OperatorIDs          []string `protobuf:"bytes,2,rep,name=operatorIDs,proto3" json:"operatorIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *DeleteRequest) GetOperatorIDs() []string {
	if m != nil {
		return m.OperatorIDs
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type DeleteMultiRequest struct {
	DeviceIDs            []uint32 `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	OperatorIDs          []string `protobuf:"bytes,2,rep,name=operatorIDs,proto3" json:"operatorIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMultiRequest) Reset()         { *m = DeleteMultiRequest{} }
func (m *DeleteMultiRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMultiRequest) ProtoMessage()    {}
func (*DeleteMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{8}
}

func (m *DeleteMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMultiRequest.Unmarshal(m, b)
}
func (m *DeleteMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMultiRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMultiRequest.Merge(m, src)
}
func (m *DeleteMultiRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMultiRequest.Size(m)
}
func (m *DeleteMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMultiRequest proto.InternalMessageInfo

func (m *DeleteMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *DeleteMultiRequest) GetOperatorIDs() []string {
	if m != nil {
		return m.OperatorIDs
	}
	return nil
}

type DeleteMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteMultiResponse) Reset()         { *m = DeleteMultiResponse{} }
func (m *DeleteMultiResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMultiResponse) ProtoMessage()    {}
func (*DeleteMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{9}
}

func (m *DeleteMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMultiResponse.Unmarshal(m, b)
}
func (m *DeleteMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMultiResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMultiResponse.Merge(m, src)
}
func (m *DeleteMultiResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMultiResponse.Size(m)
}
func (m *DeleteMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMultiResponse proto.InternalMessageInfo

func (m *DeleteMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type DeleteAllRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllRequest) Reset()         { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()    {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{10}
}

func (m *DeleteAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllRequest.Unmarshal(m, b)
}
func (m *DeleteAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllRequest.Merge(m, src)
}
func (m *DeleteAllRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllRequest.Size(m)
}
func (m *DeleteAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllRequest proto.InternalMessageInfo

func (m *DeleteAllRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type DeleteAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllResponse) Reset()         { *m = DeleteAllResponse{} }
func (m *DeleteAllResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllResponse) ProtoMessage()    {}
func (*DeleteAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{11}
}

func (m *DeleteAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllResponse.Unmarshal(m, b)
}
func (m *DeleteAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllResponse.Merge(m, src)
}
func (m *DeleteAllResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllResponse.Size(m)
}
func (m *DeleteAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllResponse proto.InternalMessageInfo

type DeleteAllMultiRequest struct {
	DeviceIDs            []uint32 `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllMultiRequest) Reset()         { *m = DeleteAllMultiRequest{} }
func (m *DeleteAllMultiRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllMultiRequest) ProtoMessage()    {}
func (*DeleteAllMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{12}
}

func (m *DeleteAllMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllMultiRequest.Unmarshal(m, b)
}
func (m *DeleteAllMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllMultiRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllMultiRequest.Merge(m, src)
}
func (m *DeleteAllMultiRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllMultiRequest.Size(m)
}
func (m *DeleteAllMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllMultiRequest proto.InternalMessageInfo

func (m *DeleteAllMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

type DeleteAllMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteAllMultiResponse) Reset()         { *m = DeleteAllMultiResponse{} }
func (m *DeleteAllMultiResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllMultiResponse) ProtoMessage()    {}
func (*DeleteAllMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8d3714996346ac, []int{13}
}

func (m *DeleteAllMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllMultiResponse.Unmarshal(m, b)
}
func (m *DeleteAllMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllMultiResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllMultiResponse.Merge(m, src)
}
func (m *DeleteAllMultiResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllMultiResponse.Size(m)
}
func (m *DeleteAllMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllMultiResponse proto.InternalMessageInfo

func (m *DeleteAllMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

func init() {
	proto.RegisterType((*GetListRequest)(nil), "operator.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "operator.GetListResponse")
	proto.RegisterType((*AddRequest)(nil), "operator.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "operator.AddResponse")
	proto.RegisterType((*AddMultiRequest)(nil), "operator.AddMultiRequest")
	proto.RegisterType((*AddMultiResponse)(nil), "operator.AddMultiResponse")
	proto.RegisterType((*DeleteRequest)(nil), "operator.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "operator.DeleteResponse")
	proto.RegisterType((*DeleteMultiRequest)(nil), "operator.DeleteMultiRequest")
	proto.RegisterType((*DeleteMultiResponse)(nil), "operator.DeleteMultiResponse")
	proto.RegisterType((*DeleteAllRequest)(nil), "operator.DeleteAllRequest")
	proto.RegisterType((*DeleteAllResponse)(nil), "operator.DeleteAllResponse")
	proto.RegisterType((*DeleteAllMultiRequest)(nil), "operator.DeleteAllMultiRequest")
	proto.RegisterType((*DeleteAllMultiResponse)(nil), "operator.DeleteAllMultiResponse")
}

func init() { proto.RegisterFile("operator.proto", fileDescriptor_cb8d3714996346ac) }

var fileDescriptor_cb8d3714996346ac = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xe6, 0x3c, 0xa8, 0x97, 0x89, 0x49, 0xcf, 0xad, 0xd5, 0x74, 0x5b, 0x31, 0xe4, 0xa9, 0x0f,
	0x25, 0x85, 0x13, 0x05, 0x11, 0x94, 0xc8, 0x89, 0x58, 0x3c, 0x2c, 0x51, 0x7c, 0x10, 0x7c, 0x48,
	0x6f, 0x17, 0x0c, 0xa6, 0x4d, 0xdc, 0xdd, 0xf8, 0x8f, 0xfd, 0x1f, 0x92, 0xec, 0x6e, 0x36, 0x1b,
	0x53, 0x9a, 0xd2, 0xb7, 0xcb, 0x37, 0xdf, 0x7c, 0x33, 0xf3, 0xed, 0xcc, 0x81, 0x5f, 0x56, 0x94,
	0x65, 0xa2, 0x64, 0x71, 0xc5, 0x4a, 0x51, 0xa2, 0x85, 0xfe, 0xc6, 0x0e, 0x65, 0x0a, 0xc4, 0x90,
	0xd5, 0xe2, 0xa7, 0xfc, 0x1d, 0x9d, 0x80, 0xff, 0x81, 0x8a, 0x4f, 0x39, 0x17, 0x29, 0xfd, 0x5d,
	0x53, 0x2e, 0x10, 0x86, 0x05, 0xa1, 0x7f, 0xf2, 0x2d, 0xfd, 0xb8, 0x0e, 0x66, 0xe1, 0xec, 0xd8,
	0x4b, 0xbb, 0xef, 0xe8, 0x2d, 0xec, 0x76, 0x6c, 0x5e, 0x95, 0x57, 0x9c, 0xa2, 0x13, 0x70, 0x74,
	0x0d, 0x1e, 0xcc, 0xc2, 0xf9, 0xb1, 0xbb, 0xf2, 0xe3, 0xb6, 0xc0, 0x67, 0x05, 0xa7, 0x86, 0x10,
	0x7d, 0x03, 0x48, 0x08, 0x99, 0x50, 0xca, 0xd6, 0xbd, 0x77, 0x93, 0xae, 0x07, 0x6e, 0xab, 0x2b,
	0x9b, 0x8a, 0x7e, 0xc0, 0x6e, 0x42, 0xc8, 0xa6, 0x2e, 0x44, 0xae, 0x6b, 0x1d, 0x81, 0xa3, 0xb5,
	0x65, 0x9f, 0x5e, 0x6a, 0x80, 0x5b, 0x56, 0x3b, 0x83, 0xa5, 0x91, 0x57, 0x3e, 0xbc, 0x84, 0x07,
	0x52, 0xee, 0x3d, 0x63, 0xc6, 0x0a, 0x14, 0x37, 0xb6, 0xb7, 0x90, 0x66, 0xa6, 0x16, 0x2f, 0xda,
	0x80, 0xb7, 0xa6, 0x05, 0x15, 0x74, 0x8a, 0x29, 0x21, 0xb8, 0xba, 0x8b, 0x66, 0x8c, 0xa6, 0x51,
	0x27, 0xed, 0x43, 0xd1, 0x12, 0x7c, 0x2d, 0xa7, 0xbc, 0xf8, 0x0a, 0x48, 0x22, 0xb7, 0xb0, 0xe3,
	0xe6, 0x3a, 0x1b, 0xd8, 0xb3, 0x54, 0xef, 0xe8, 0x42, 0x0c, 0x4b, 0x29, 0x97, 0x14, 0xc5, 0x94,
	0x45, 0xdc, 0x83, 0x87, 0x3d, 0xbe, 0x9a, 0xf4, 0x05, 0xec, 0x77, 0xe0, 0xf4, 0x61, 0xa3, 0x73,
	0x78, 0x3c, 0x4c, 0xbb, 0xdb, 0x34, 0xab, 0xbf, 0x73, 0x58, 0xe8, 0xbd, 0x41, 0x6f, 0xe0, 0xbe,
	0xba, 0x19, 0x14, 0xc4, 0xdd, 0x79, 0xda, 0x47, 0x87, 0x0f, 0x46, 0x22, 0xaa, 0x89, 0x15, 0xcc,
	0x13, 0x42, 0xd0, 0x23, 0xc3, 0x30, 0x17, 0x84, 0xf7, 0x07, 0xa8, 0xca, 0x49, 0x60, 0xa1, 0x17,
	0x14, 0x1d, 0x58, 0x94, 0xbe, 0x2f, 0x18, 0x8f, 0x85, 0x94, 0xc4, 0x6b, 0xd8, 0x91, 0xae, 0xa0,
	0x27, 0x86, 0x65, 0x6d, 0x2a, 0x0e, 0xfe, 0x0f, 0xa8, 0xe4, 0x33, 0x70, 0x7b, 0xdb, 0x81, 0x8e,
	0x86, 0x44, 0xab, 0x8b, 0xa7, 0xd7, 0x44, 0x95, 0xd6, 0x1a, 0x9c, 0xee, 0x79, 0x10, 0x1e, 0x72,
	0xcd, 0xbe, 0xe0, 0xc3, 0xd1, 0x98, 0x52, 0xf9, 0xa2, 0xef, 0x42, 0x3f, 0x32, 0x7a, 0x36, 0x42,
	0xb7, 0xfa, 0x0a, 0xaf, 0x27, 0x48, 0xd1, 0x77, 0xaf, 0xe0, 0x70, 0x5b, 0x5e, 0xc6, 0xbc, 0xae,
	0x18, 0xbd, 0xcc, 0xf2, 0xab, 0x6d, 0xcc, 0xc9, 0xaf, 0x2e, 0xeb, 0x7c, 0xf6, 0x3d, 0xb8, 0xc8,
	0x4b, 0x2e, 0x32, 0x76, 0xca, 0x29, 0x6b, 0xf6, 0xe3, 0x54, 0xc7, 0x2e, 0x76, 0xda, 0xbf, 0xdf,
	0xe7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xb2, 0xbf, 0x6c, 0xb1, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OperatorClient is the client API for Operator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperatorClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	AddMulti(ctx context.Context, in *AddMultiRequest, opts ...grpc.CallOption) (*AddMultiResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteMulti(ctx context.Context, in *DeleteMultiRequest, opts ...grpc.CallOption) (*DeleteMultiResponse, error)
	DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error)
	DeleteAllMulti(ctx context.Context, in *DeleteAllMultiRequest, opts ...grpc.CallOption) (*DeleteAllMultiResponse, error)
}

type operatorClient struct {
	cc *grpc.ClientConn
}

func NewOperatorClient(cc *grpc.ClientConn) OperatorClient {
	return &operatorClient{cc}
}

func (c *operatorClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/operator.Operator/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/operator.Operator/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) AddMulti(ctx context.Context, in *AddMultiRequest, opts ...grpc.CallOption) (*AddMultiResponse, error) {
	out := new(AddMultiResponse)
	err := c.cc.Invoke(ctx, "/operator.Operator/AddMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/operator.Operator/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) DeleteMulti(ctx context.Context, in *DeleteMultiRequest, opts ...grpc.CallOption) (*DeleteMultiResponse, error) {
	out := new(DeleteMultiResponse)
	err := c.cc.Invoke(ctx, "/operator.Operator/DeleteMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error) {
	out := new(DeleteAllResponse)
	err := c.cc.Invoke(ctx, "/operator.Operator/DeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) DeleteAllMulti(ctx context.Context, in *DeleteAllMultiRequest, opts ...grpc.CallOption) (*DeleteAllMultiResponse, error) {
	out := new(DeleteAllMultiResponse)
	err := c.cc.Invoke(ctx, "/operator.Operator/DeleteAllMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServer is the server API for Operator service.
type OperatorServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	AddMulti(context.Context, *AddMultiRequest) (*AddMultiResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteMulti(context.Context, *DeleteMultiRequest) (*DeleteMultiResponse, error)
	DeleteAll(context.Context, *DeleteAllRequest) (*DeleteAllResponse, error)
	DeleteAllMulti(context.Context, *DeleteAllMultiRequest) (*DeleteAllMultiResponse, error)
}

func RegisterOperatorServer(s *grpc.Server, srv OperatorServer) {
	s.RegisterService(&_Operator_serviceDesc, srv)
}

func _Operator_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.Operator/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.Operator/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_AddMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).AddMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.Operator/AddMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).AddMulti(ctx, req.(*AddMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.Operator/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_DeleteMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).DeleteMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.Operator/DeleteMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).DeleteMulti(ctx, req.(*DeleteMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.Operator/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).DeleteAll(ctx, req.(*DeleteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_DeleteAllMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).DeleteAllMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operator.Operator/DeleteAllMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).DeleteAllMulti(ctx, req.(*DeleteAllMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Operator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "operator.Operator",
	HandlerType: (*OperatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _Operator_GetList_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Operator_Add_Handler,
		},
		{
			MethodName: "AddMulti",
			Handler:    _Operator_AddMulti_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Operator_Delete_Handler,
		},
		{
			MethodName: "DeleteMulti",
			Handler:    _Operator_DeleteMulti_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _Operator_DeleteAll_Handler,
		},
		{
			MethodName: "DeleteAllMulti",
			Handler:    _Operator_DeleteAllMulti_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator.proto",
}
