// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voip.proto

package voip

import (
	err "biostar/service/err"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserPhone struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPhone) Reset()         { *m = UserPhone{} }
func (m *UserPhone) String() string { return proto.CompactTextString(m) }
func (*UserPhone) ProtoMessage()    {}
func (*UserPhone) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{0}
}

func (m *UserPhone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPhone.Unmarshal(m, b)
}
func (m *UserPhone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPhone.Marshal(b, m, deterministic)
}
func (m *UserPhone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPhone.Merge(m, src)
}
func (m *UserPhone) XXX_Size() int {
	return xxx_messageInfo_UserPhone.Size(m)
}
func (m *UserPhone) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPhone.DiscardUnknown(m)
}

var xxx_messageInfo_UserPhone proto.InternalMessageInfo

func (m *UserPhone) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserPhone) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type VOIPConfig struct {
	ServerURL            string       `protobuf:"bytes,1,opt,name=serverURL,proto3" json:"serverURL,omitempty"`
	ServerPort           uint32       `protobuf:"varint,2,opt,name=serverPort,proto3" json:"serverPort,omitempty"`
	UserID               string       `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	UserPW               string       `protobuf:"bytes,4,opt,name=userPW,proto3" json:"userPW,omitempty"`
	Enabled              bool         `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ExitButton           uint32       `protobuf:"varint,6,opt,name=exitButton,proto3" json:"exitButton,omitempty"`
	DTMFMode             uint32       `protobuf:"varint,7,opt,name=DTMFMode,proto3" json:"DTMFMode,omitempty"`
	Phones               []*UserPhone `protobuf:"bytes,8,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VOIPConfig) Reset()         { *m = VOIPConfig{} }
func (m *VOIPConfig) String() string { return proto.CompactTextString(m) }
func (*VOIPConfig) ProtoMessage()    {}
func (*VOIPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{1}
}

func (m *VOIPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VOIPConfig.Unmarshal(m, b)
}
func (m *VOIPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VOIPConfig.Marshal(b, m, deterministic)
}
func (m *VOIPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VOIPConfig.Merge(m, src)
}
func (m *VOIPConfig) XXX_Size() int {
	return xxx_messageInfo_VOIPConfig.Size(m)
}
func (m *VOIPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VOIPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VOIPConfig proto.InternalMessageInfo

func (m *VOIPConfig) GetServerURL() string {
	if m != nil {
		return m.ServerURL
	}
	return ""
}

func (m *VOIPConfig) GetServerPort() uint32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

func (m *VOIPConfig) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *VOIPConfig) GetUserPW() string {
	if m != nil {
		return m.UserPW
	}
	return ""
}

func (m *VOIPConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *VOIPConfig) GetExitButton() uint32 {
	if m != nil {
		return m.ExitButton
	}
	return 0
}

func (m *VOIPConfig) GetDTMFMode() uint32 {
	if m != nil {
		return m.DTMFMode
	}
	return 0
}

func (m *VOIPConfig) GetPhones() []*UserPhone {
	if m != nil {
		return m.Phones
	}
	return nil
}

type GetConfigRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{2}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetConfigResponse struct {
	Config               *VOIPConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{3}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetConfig() *VOIPConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigRequest struct {
	DeviceID             uint32      `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Config               *VOIPConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{4}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetConfigRequest) GetConfig() *VOIPConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{5}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

type SetConfigMultiRequest struct {
	DeviceIDs            []uint32    `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	Config               *VOIPConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfigMultiRequest) Reset()         { *m = SetConfigMultiRequest{} }
func (m *SetConfigMultiRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiRequest) ProtoMessage()    {}
func (*SetConfigMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{6}
}

func (m *SetConfigMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiRequest.Unmarshal(m, b)
}
func (m *SetConfigMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiRequest.Merge(m, src)
}
func (m *SetConfigMultiRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiRequest.Size(m)
}
func (m *SetConfigMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiRequest proto.InternalMessageInfo

func (m *SetConfigMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *SetConfigMultiRequest) GetConfig() *VOIPConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetConfigMultiResponse) Reset()         { *m = SetConfigMultiResponse{} }
func (m *SetConfigMultiResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiResponse) ProtoMessage()    {}
func (*SetConfigMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec738bcdae35d5a8, []int{7}
}

func (m *SetConfigMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiResponse.Unmarshal(m, b)
}
func (m *SetConfigMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiResponse.Merge(m, src)
}
func (m *SetConfigMultiResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiResponse.Size(m)
}
func (m *SetConfigMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiResponse proto.InternalMessageInfo

func (m *SetConfigMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

func init() {
	proto.RegisterType((*UserPhone)(nil), "voip.UserPhone")
	proto.RegisterType((*VOIPConfig)(nil), "voip.VOIPConfig")
	proto.RegisterType((*GetConfigRequest)(nil), "voip.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "voip.GetConfigResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "voip.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "voip.SetConfigResponse")
	proto.RegisterType((*SetConfigMultiRequest)(nil), "voip.SetConfigMultiRequest")
	proto.RegisterType((*SetConfigMultiResponse)(nil), "voip.SetConfigMultiResponse")
}

func init() { proto.RegisterFile("voip.proto", fileDescriptor_ec738bcdae35d5a8) }

var fileDescriptor_ec738bcdae35d5a8 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0x95, 0xad, 0x74, 0xcd, 0x2d, 0x85, 0xce, 0x40, 0x67, 0x95, 0x0a, 0x55, 0x79, 0x21,
	0x4f, 0x99, 0x28, 0x12, 0x4f, 0xe3, 0x65, 0x14, 0x50, 0x05, 0x65, 0x91, 0xcb, 0x18, 0xe2, 0x05,
	0xb5, 0xc9, 0x05, 0x2c, 0xd6, 0x38, 0xd8, 0x4e, 0xc5, 0xb7, 0xe4, 0xf3, 0xf0, 0x86, 0x62, 0xe7,
	0xdf, 0x32, 0x10, 0xda, 0x5b, 0xee, 0xef, 0xde, 0x7b, 0x8e, 0x7d, 0x5a, 0x03, 0xec, 0x04, 0x4f,
	0x83, 0x54, 0x0a, 0x2d, 0x48, 0x27, 0xff, 0x1e, 0xbb, 0x28, 0xa5, 0x05, 0xde, 0x19, 0xb8, 0xe7,
	0x0a, 0x65, 0xf8, 0x4d, 0x24, 0x48, 0xa6, 0xd0, 0x4f, 0xf3, 0x8f, 0x77, 0xd9, 0x76, 0x83, 0x92,
	0x3a, 0x53, 0xc7, 0x77, 0x59, 0x13, 0xe5, 0x13, 0x31, 0xaa, 0x48, 0xf2, 0x54, 0x73, 0x91, 0xd0,
	0x3d, 0x3b, 0xd1, 0x40, 0xde, 0x6f, 0x07, 0xe0, 0xc3, 0xd9, 0x22, 0x7c, 0x21, 0x92, 0x2f, 0xfc,
	0x2b, 0x99, 0x80, 0xab, 0x50, 0xee, 0x50, 0x9e, 0xb3, 0xb7, 0x85, 0x60, 0x0d, 0xc8, 0x23, 0x00,
	0x5b, 0x84, 0x42, 0x6a, 0xa3, 0x36, 0x60, 0x0d, 0x42, 0x46, 0xd0, 0xcd, 0x14, 0xca, 0xc5, 0x9c,
	0xee, 0x9b, 0xd5, 0xa2, 0x2a, 0x79, 0x78, 0x41, 0x3b, 0x35, 0x0f, 0x2f, 0x08, 0x85, 0x03, 0x4c,
	0xd6, 0x9b, 0x4b, 0x8c, 0xe9, 0xad, 0xa9, 0xe3, 0xf7, 0x58, 0x59, 0xe6, 0x4e, 0xf8, 0x93, 0xeb,
	0xd3, 0x4c, 0x6b, 0x91, 0xd0, 0xae, 0x75, 0xaa, 0x09, 0x19, 0x43, 0x6f, 0xfe, 0x7e, 0xf9, 0x6a,
	0x29, 0x62, 0xa4, 0x07, 0xa6, 0x5b, 0xd5, 0xe4, 0x31, 0x74, 0x4d, 0x06, 0x8a, 0xf6, 0xa6, 0xfb,
	0x7e, 0x7f, 0x76, 0x37, 0x30, 0x89, 0x56, 0xb9, 0xb1, 0xa2, 0xed, 0x05, 0x30, 0x7c, 0x8d, 0xda,
	0xde, 0x9c, 0xe1, 0x8f, 0x0c, 0x95, 0xce, 0x85, 0x63, 0xdc, 0xf1, 0x08, 0x17, 0x73, 0x73, 0xff,
	0x01, 0xab, 0x6a, 0xef, 0x39, 0x1c, 0x36, 0xe6, 0x55, 0x2a, 0x12, 0x85, 0xc4, 0x87, 0x6e, 0x64,
	0x88, 0x19, 0xef, 0xcf, 0x86, 0xd6, 0xad, 0xce, 0x94, 0x15, 0x7d, 0xef, 0x23, 0x0c, 0x57, 0x37,
	0xb0, 0x6b, 0x28, 0xef, 0xfd, 0x47, 0xf9, 0x1e, 0x1c, 0xae, 0xda, 0x07, 0xf3, 0x3e, 0xc3, 0x83,
	0x0a, 0x2e, 0xb3, 0x4b, 0xcd, 0x4b, 0xcf, 0x09, 0xb8, 0xa5, 0x87, 0xa2, 0xce, 0x74, 0xdf, 0x1f,
	0xb0, 0x1a, 0xdc, 0xc0, 0x35, 0x84, 0x51, 0xdb, 0xa0, 0xc8, 0xe4, 0x19, 0xdc, 0xb6, 0x82, 0x2f,
	0xa5, 0x14, 0xd2, 0x9a, 0xf4, 0x67, 0x24, 0xc8, 0xff, 0xc7, 0x06, 0x95, 0x93, 0xec, 0xca, 0xdc,
	0xec, 0x97, 0x03, 0x9d, 0xdc, 0x88, 0x9c, 0x80, 0x5b, 0x25, 0x4d, 0x46, 0xf6, 0x04, 0xed, 0x9f,
	0x6a, 0x7c, 0x74, 0x8d, 0x17, 0xf6, 0x27, 0xe0, 0xae, 0xda, 0xdb, 0xab, 0x7f, 0x6c, 0x5f, 0xcb,
	0x8d, 0xbc, 0x81, 0x3b, 0x57, 0xaf, 0x45, 0x1e, 0xb6, 0x46, 0x9b, 0x69, 0x8e, 0x27, 0x7f, 0x6f,
	0x5a, 0xb1, 0xd3, 0x27, 0x70, 0x14, 0x89, 0x6d, 0xa0, 0xb2, 0x54, 0xe2, 0x76, 0xcd, 0x93, 0x28,
	0x50, 0xf1, 0x77, 0xb3, 0x11, 0x3a, 0x9f, 0xee, 0x6f, 0xb8, 0x50, 0x7a, 0x2d, 0x8f, 0xf3, 0x27,
	0xc4, 0x23, 0x3c, 0xce, 0xf9, 0xa6, 0x6b, 0x5e, 0xfa, 0xd3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd9, 0xfe, 0x0c, 0x67, 0x08, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VOIPClient is the client API for VOIP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VOIPClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error)
}

type vOIPClient struct {
	cc *grpc.ClientConn
}

func NewVOIPClient(cc *grpc.ClientConn) VOIPClient {
	return &vOIPClient{cc}
}

func (c *vOIPClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/voip.VOIP/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOIPClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/voip.VOIP/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOIPClient) SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error) {
	out := new(SetConfigMultiResponse)
	err := c.cc.Invoke(ctx, "/voip.VOIP/SetConfigMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VOIPServer is the server API for VOIP service.
type VOIPServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	SetConfigMulti(context.Context, *SetConfigMultiRequest) (*SetConfigMultiResponse, error)
}

func RegisterVOIPServer(s *grpc.Server, srv VOIPServer) {
	s.RegisterService(&_VOIP_serviceDesc, srv)
}

func _VOIP_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOIPServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voip.VOIP/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOIPServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOIP_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOIPServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voip.VOIP/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOIPServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOIP_SetConfigMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOIPServer).SetConfigMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voip.VOIP/SetConfigMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOIPServer).SetConfigMulti(ctx, req.(*SetConfigMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VOIP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "voip.VOIP",
	HandlerType: (*VOIPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _VOIP_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _VOIP_SetConfig_Handler,
		},
		{
			MethodName: "SetConfigMulti",
			Handler:    _VOIP_SetConfigMulti_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voip.proto",
}
