// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timed_apb_zone.proto

package timedApbZone

import (
	action "biostar/service/action"
	zone "biostar/service/zone"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_HARD Type = 0
	Type_SOFT Type = 1
)

var Type_name = map[int32]string{
	0: "HARD",
	1: "SOFT",
}

var Type_value = map[string]int32{
	"HARD": 0,
	"SOFT": 1,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{0}
}

type Member struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{0}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type ZoneInfo struct {
	ZoneID               uint32           `protobuf:"varint,1,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Type             `protobuf:"varint,3,opt,name=type,proto3,enum=timed_apb_zone.Type" json:"type,omitempty"`
	Disabled             bool             `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Alarmed              bool             `protobuf:"varint,5,opt,name=alarmed,proto3" json:"alarmed,omitempty"`
	ResetDuration        uint32           `protobuf:"varint,6,opt,name=resetDuration,proto3" json:"resetDuration,omitempty"`
	Members              []*Member        `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	Actions              []*action.Action `protobuf:"bytes,8,rep,name=actions,proto3" json:"actions,omitempty"`
	BypassGroupIDs       []uint32         `protobuf:"varint,9,rep,packed,name=bypassGroupIDs,proto3" json:"bypassGroupIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ZoneInfo) Reset()         { *m = ZoneInfo{} }
func (m *ZoneInfo) String() string { return proto.CompactTextString(m) }
func (*ZoneInfo) ProtoMessage()    {}
func (*ZoneInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{1}
}

func (m *ZoneInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneInfo.Unmarshal(m, b)
}
func (m *ZoneInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneInfo.Marshal(b, m, deterministic)
}
func (m *ZoneInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneInfo.Merge(m, src)
}
func (m *ZoneInfo) XXX_Size() int {
	return xxx_messageInfo_ZoneInfo.Size(m)
}
func (m *ZoneInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneInfo proto.InternalMessageInfo

func (m *ZoneInfo) GetZoneID() uint32 {
	if m != nil {
		return m.ZoneID
	}
	return 0
}

func (m *ZoneInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ZoneInfo) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_HARD
}

func (m *ZoneInfo) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *ZoneInfo) GetAlarmed() bool {
	if m != nil {
		return m.Alarmed
	}
	return false
}

func (m *ZoneInfo) GetResetDuration() uint32 {
	if m != nil {
		return m.ResetDuration
	}
	return 0
}

func (m *ZoneInfo) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *ZoneInfo) GetActions() []*action.Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *ZoneInfo) GetBypassGroupIDs() []uint32 {
	if m != nil {
		return m.BypassGroupIDs
	}
	return nil
}

type GetRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetResponse struct {
	Zones                []*ZoneInfo `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetZones() []*ZoneInfo {
	if m != nil {
		return m.Zones
	}
	return nil
}

type GetStatusRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneIDs              []uint32 `protobuf:"varint,2,rep,packed,name=zoneIDs,proto3" json:"zoneIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{4}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

func (m *GetStatusRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *GetStatusRequest) GetZoneIDs() []uint32 {
	if m != nil {
		return m.ZoneIDs
	}
	return nil
}

type GetStatusResponse struct {
	Status               []*zone.ZoneStatus `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{5}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetStatus() []*zone.ZoneStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type AddRequest struct {
	DeviceID             uint32      `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Zones                []*ZoneInfo `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{6}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *AddRequest) GetZones() []*ZoneInfo {
	if m != nil {
		return m.Zones
	}
	return nil
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{7}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

type DeleteRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneIDs              []uint32 `protobuf:"varint,2,rep,packed,name=zoneIDs,proto3" json:"zoneIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *DeleteRequest) GetZoneIDs() []uint32 {
	if m != nil {
		return m.ZoneIDs
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type DeleteAllRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllRequest) Reset()         { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()    {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{10}
}

func (m *DeleteAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllRequest.Unmarshal(m, b)
}
func (m *DeleteAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllRequest.Merge(m, src)
}
func (m *DeleteAllRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllRequest.Size(m)
}
func (m *DeleteAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllRequest proto.InternalMessageInfo

func (m *DeleteAllRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type DeleteAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllResponse) Reset()         { *m = DeleteAllResponse{} }
func (m *DeleteAllResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllResponse) ProtoMessage()    {}
func (*DeleteAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{11}
}

func (m *DeleteAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllResponse.Unmarshal(m, b)
}
func (m *DeleteAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllResponse.Merge(m, src)
}
func (m *DeleteAllResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllResponse.Size(m)
}
func (m *DeleteAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllResponse proto.InternalMessageInfo

type ClearRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneID               uint32   `protobuf:"varint,2,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	UserIDs              []string `protobuf:"bytes,3,rep,name=userIDs,proto3" json:"userIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{12}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

func (m *ClearRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *ClearRequest) GetZoneID() uint32 {
	if m != nil {
		return m.ZoneID
	}
	return 0
}

func (m *ClearRequest) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type ClearResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearResponse) Reset()         { *m = ClearResponse{} }
func (m *ClearResponse) String() string { return proto.CompactTextString(m) }
func (*ClearResponse) ProtoMessage()    {}
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{13}
}

func (m *ClearResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearResponse.Unmarshal(m, b)
}
func (m *ClearResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearResponse.Marshal(b, m, deterministic)
}
func (m *ClearResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearResponse.Merge(m, src)
}
func (m *ClearResponse) XXX_Size() int {
	return xxx_messageInfo_ClearResponse.Size(m)
}
func (m *ClearResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearResponse proto.InternalMessageInfo

type ClearAllRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneID               uint32   `protobuf:"varint,2,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearAllRequest) Reset()         { *m = ClearAllRequest{} }
func (m *ClearAllRequest) String() string { return proto.CompactTextString(m) }
func (*ClearAllRequest) ProtoMessage()    {}
func (*ClearAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{14}
}

func (m *ClearAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearAllRequest.Unmarshal(m, b)
}
func (m *ClearAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearAllRequest.Marshal(b, m, deterministic)
}
func (m *ClearAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearAllRequest.Merge(m, src)
}
func (m *ClearAllRequest) XXX_Size() int {
	return xxx_messageInfo_ClearAllRequest.Size(m)
}
func (m *ClearAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearAllRequest proto.InternalMessageInfo

func (m *ClearAllRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *ClearAllRequest) GetZoneID() uint32 {
	if m != nil {
		return m.ZoneID
	}
	return 0
}

type ClearAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearAllResponse) Reset()         { *m = ClearAllResponse{} }
func (m *ClearAllResponse) String() string { return proto.CompactTextString(m) }
func (*ClearAllResponse) ProtoMessage()    {}
func (*ClearAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{15}
}

func (m *ClearAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearAllResponse.Unmarshal(m, b)
}
func (m *ClearAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearAllResponse.Marshal(b, m, deterministic)
}
func (m *ClearAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearAllResponse.Merge(m, src)
}
func (m *ClearAllResponse) XXX_Size() int {
	return xxx_messageInfo_ClearAllResponse.Size(m)
}
func (m *ClearAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearAllResponse proto.InternalMessageInfo

type SetAlarmRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	ZoneIDs              []uint32 `protobuf:"varint,2,rep,packed,name=zoneIDs,proto3" json:"zoneIDs,omitempty"`
	Alarmed              bool     `protobuf:"varint,3,opt,name=alarmed,proto3" json:"alarmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmRequest) Reset()         { *m = SetAlarmRequest{} }
func (m *SetAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*SetAlarmRequest) ProtoMessage()    {}
func (*SetAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{16}
}

func (m *SetAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmRequest.Unmarshal(m, b)
}
func (m *SetAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmRequest.Marshal(b, m, deterministic)
}
func (m *SetAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmRequest.Merge(m, src)
}
func (m *SetAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_SetAlarmRequest.Size(m)
}
func (m *SetAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmRequest proto.InternalMessageInfo

func (m *SetAlarmRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetAlarmRequest) GetZoneIDs() []uint32 {
	if m != nil {
		return m.ZoneIDs
	}
	return nil
}

func (m *SetAlarmRequest) GetAlarmed() bool {
	if m != nil {
		return m.Alarmed
	}
	return false
}

type SetAlarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmResponse) Reset()         { *m = SetAlarmResponse{} }
func (m *SetAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*SetAlarmResponse) ProtoMessage()    {}
func (*SetAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b057ab17569c9084, []int{17}
}

func (m *SetAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmResponse.Unmarshal(m, b)
}
func (m *SetAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmResponse.Marshal(b, m, deterministic)
}
func (m *SetAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmResponse.Merge(m, src)
}
func (m *SetAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_SetAlarmResponse.Size(m)
}
func (m *SetAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("timed_apb_zone.Type", Type_name, Type_value)
	proto.RegisterType((*Member)(nil), "timed_apb_zone.Member")
	proto.RegisterType((*ZoneInfo)(nil), "timed_apb_zone.ZoneInfo")
	proto.RegisterType((*GetRequest)(nil), "timed_apb_zone.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "timed_apb_zone.GetResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "timed_apb_zone.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "timed_apb_zone.GetStatusResponse")
	proto.RegisterType((*AddRequest)(nil), "timed_apb_zone.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "timed_apb_zone.AddResponse")
	proto.RegisterType((*DeleteRequest)(nil), "timed_apb_zone.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "timed_apb_zone.DeleteResponse")
	proto.RegisterType((*DeleteAllRequest)(nil), "timed_apb_zone.DeleteAllRequest")
	proto.RegisterType((*DeleteAllResponse)(nil), "timed_apb_zone.DeleteAllResponse")
	proto.RegisterType((*ClearRequest)(nil), "timed_apb_zone.ClearRequest")
	proto.RegisterType((*ClearResponse)(nil), "timed_apb_zone.ClearResponse")
	proto.RegisterType((*ClearAllRequest)(nil), "timed_apb_zone.ClearAllRequest")
	proto.RegisterType((*ClearAllResponse)(nil), "timed_apb_zone.ClearAllResponse")
	proto.RegisterType((*SetAlarmRequest)(nil), "timed_apb_zone.SetAlarmRequest")
	proto.RegisterType((*SetAlarmResponse)(nil), "timed_apb_zone.SetAlarmResponse")
}

func init() { proto.RegisterFile("timed_apb_zone.proto", fileDescriptor_b057ab17569c9084) }

var fileDescriptor_b057ab17569c9084 = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x4f, 0xdb, 0x4a,
	0x10, 0xbd, 0x8e, 0x43, 0x3e, 0x06, 0x12, 0xc2, 0x5e, 0x84, 0x56, 0xbe, 0xdc, 0x7b, 0x8d, 0x85,
	0x2a, 0xab, 0x0f, 0xa6, 0xa2, 0xcf, 0x20, 0x19, 0xd2, 0x06, 0x1e, 0x50, 0x91, 0xe1, 0xa1, 0x42,
	0x95, 0x90, 0x1d, 0x4f, 0xa5, 0xa8, 0xf1, 0x47, 0xbd, 0x9b, 0x4a, 0xf4, 0xd7, 0xf5, 0x9f, 0xf4,
	0xaf, 0x54, 0xbb, 0x5e, 0xdb, 0x89, 0x4d, 0x50, 0x24, 0x9e, 0xe2, 0xd9, 0x39, 0x9e, 0x39, 0x33,
	0x7b, 0x4e, 0x0c, 0xfb, 0x7c, 0x16, 0x61, 0xf8, 0xe8, 0xa7, 0xc1, 0xe3, 0xcf, 0x24, 0x46, 0x27,
	0xcd, 0x12, 0x9e, 0x90, 0xe1, 0xea, 0xa9, 0x01, 0x55, 0xce, 0xd8, 0xf1, 0xa7, 0x7c, 0x96, 0xc4,
	0x79, 0x64, 0x1d, 0x43, 0xe7, 0x06, 0xa3, 0x00, 0x33, 0x62, 0x40, 0x2f, 0xc4, 0x1f, 0xb3, 0x29,
	0x5e, 0x8f, 0xa9, 0x66, 0x6a, 0xf6, 0xc0, 0x2b, 0x63, 0xeb, 0x57, 0x0b, 0x7a, 0x0f, 0x49, 0x8c,
	0xd7, 0xf1, 0xd7, 0x84, 0x1c, 0x40, 0x47, 0x94, 0x2b, 0x61, 0x2a, 0x22, 0x04, 0xda, 0xb1, 0x1f,
	0x21, 0x6d, 0x99, 0x9a, 0xdd, 0xf7, 0xe4, 0x33, 0xb1, 0xa1, 0xcd, 0x9f, 0x52, 0xa4, 0xba, 0xa9,
	0xd9, 0xc3, 0xd3, 0x7d, 0xa7, 0xc6, 0xf6, 0xfe, 0x29, 0x45, 0x4f, 0x22, 0x64, 0xfb, 0x19, 0xf3,
	0x83, 0x39, 0x86, 0xb4, 0x6d, 0x6a, 0x76, 0xcf, 0x2b, 0x63, 0x42, 0xa1, 0xeb, 0xcf, 0xfd, 0x2c,
	0xc2, 0x90, 0x6e, 0xc9, 0x54, 0x11, 0x92, 0x63, 0x18, 0x64, 0xc8, 0x90, 0x8f, 0x17, 0x99, 0x2f,
	0xa6, 0xa2, 0x1d, 0x49, 0x69, 0xf5, 0x90, 0xbc, 0x83, 0x6e, 0x24, 0x87, 0x64, 0xb4, 0x6b, 0xea,
	0xf6, 0xf6, 0xe9, 0x41, 0x9d, 0x48, 0xbe, 0x03, 0xaf, 0x80, 0x11, 0x1b, 0xba, 0xf9, 0x9a, 0x18,
	0xed, 0xc9, 0x37, 0x86, 0x8e, 0x5a, 0x9b, 0x2b, 0x7f, 0xbc, 0x22, 0x4d, 0xde, 0xc0, 0x30, 0x78,
	0x4a, 0x7d, 0xc6, 0x26, 0x59, 0xb2, 0x48, 0xaf, 0xc7, 0x8c, 0xf6, 0x4d, 0xdd, 0x1e, 0x78, 0xb5,
	0x53, 0xcb, 0x06, 0x98, 0x20, 0xf7, 0xf0, 0xfb, 0x02, 0x19, 0x7f, 0x71, 0xd9, 0x67, 0xb0, 0x2d,
	0x91, 0x2c, 0x4d, 0x62, 0x86, 0xc4, 0x81, 0x2d, 0x41, 0x91, 0x51, 0x4d, 0x12, 0xa1, 0x75, 0xea,
	0xc5, 0xbd, 0x78, 0x39, 0xcc, 0xba, 0x82, 0xd1, 0x04, 0xf9, 0x1d, 0xf7, 0xf9, 0x82, 0x6d, 0xd0,
	0x4e, 0x2c, 0x37, 0xbf, 0x40, 0x46, 0x5b, 0x92, 0x79, 0x11, 0x5a, 0x67, 0xb0, 0xb7, 0x54, 0x49,
	0xd1, 0xb1, 0xa1, 0xc3, 0xe4, 0x89, 0xe2, 0x33, 0x72, 0x4a, 0x16, 0x0a, 0xa9, 0xf2, 0xd6, 0x67,
	0x00, 0x37, 0x0c, 0x37, 0xa1, 0x50, 0x8e, 0xd8, 0xda, 0x6c, 0xc4, 0x01, 0x6c, 0xcb, 0xca, 0x39,
	0x25, 0xeb, 0x03, 0x0c, 0xc6, 0x38, 0x47, 0x8e, 0xaf, 0x1b, 0x77, 0x04, 0xc3, 0xa2, 0x8c, 0x2a,
	0xec, 0xc0, 0x28, 0x3f, 0x71, 0xe7, 0xf3, 0x4d, 0x6e, 0xee, 0x6f, 0xd8, 0x5b, 0xc2, 0xab, 0x22,
	0x5f, 0x60, 0xe7, 0x72, 0x8e, 0x7e, 0xb6, 0x09, 0xb9, 0xca, 0x5a, 0xad, 0x15, 0x6b, 0x51, 0xe8,
	0x2e, 0x18, 0x66, 0x82, 0xb4, 0x6e, 0xea, 0x76, 0xdf, 0x2b, 0x42, 0x6b, 0x17, 0x06, 0xaa, 0x7a,
	0xb9, 0x8c, 0x5d, 0x79, 0xb0, 0x19, 0xe5, 0x75, 0x1d, 0x2d, 0x02, 0xa3, 0xaa, 0x8c, 0x2a, 0xed,
	0xc3, 0xee, 0x1d, 0x72, 0x57, 0x58, 0xef, 0x55, 0x9b, 0x5e, 0xf6, 0xb3, 0xbe, 0xe2, 0x67, 0xd1,
	0xb6, 0x6a, 0x91, 0xb7, 0x7d, 0x6b, 0x40, 0x5b, 0xfc, 0x4f, 0x90, 0x1e, 0xb4, 0xaf, 0x5c, 0x6f,
	0x3c, 0xfa, 0x4b, 0x3c, 0xdd, 0x7d, 0xfa, 0x78, 0x3f, 0xd2, 0x4e, 0x7f, 0xb7, 0x61, 0xe7, 0x5e,
	0x88, 0xc5, 0xbd, 0xbd, 0x10, 0x2a, 0x21, 0xe7, 0xa0, 0x4f, 0x90, 0x13, 0xa3, 0x2e, 0xa1, 0xca,
	0x7b, 0xc6, 0x3f, 0xcf, 0xe6, 0x94, 0xbc, 0x6f, 0xa1, 0x5f, 0x6a, 0x9e, 0x98, 0xcf, 0x20, 0x57,
	0x8c, 0x65, 0x1c, 0xbd, 0x80, 0x50, 0x15, 0xcf, 0x41, 0x77, 0xc3, 0xb0, 0xc9, 0xa8, 0xf2, 0x46,
	0x93, 0xd1, 0x92, 0xba, 0xc9, 0x18, 0xb6, 0xe4, 0x4d, 0x90, 0xc3, 0x3a, 0x6a, 0x59, 0x56, 0xc6,
	0xbf, 0x6b, 0xb2, 0xaa, 0xca, 0x0d, 0xf4, 0x8a, 0xfb, 0x24, 0xff, 0x3f, 0x0b, 0xad, 0x04, 0x63,
	0x98, 0xeb, 0x01, 0xaa, 0xdc, 0x04, 0x3a, 0xb9, 0xd2, 0x49, 0xa3, 0xef, 0x8a, 0x15, 0x8d, 0xff,
	0xd6, 0xa5, 0xab, 0x7d, 0x97, 0x96, 0x69, 0xee, 0xbb, 0xee, 0xbe, 0xe6, 0xbe, 0x1b, 0x7e, 0x13,
	0x93, 0x16, 0x12, 0x6a, 0x4e, 0x5a, 0xd3, 0x6f, 0x73, 0xd2, 0xba, 0xfa, 0x2e, 0x2e, 0xe1, 0x68,
	0x9a, 0x44, 0x0e, 0x5b, 0xa4, 0x19, 0x46, 0xfe, 0x2c, 0x9e, 0x3a, 0x2c, 0xfc, 0x56, 0x7b, 0xeb,
	0x56, 0x7b, 0x38, 0x0c, 0x66, 0x09, 0xe3, 0x7e, 0x76, 0xc2, 0x30, 0x13, 0xfa, 0x3f, 0x91, 0x08,
	0x37, 0x0d, 0x84, 0x2a, 0x83, 0x8e, 0xfc, 0xd8, 0xbe, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x86,
	0xa2, 0xcd, 0xdf, 0xae, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TimedAPBZoneClient is the client API for TimedAPBZone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimedAPBZoneClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	ClearAll(ctx context.Context, in *ClearAllRequest, opts ...grpc.CallOption) (*ClearAllResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error)
	SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error)
}

type timedAPBZoneClient struct {
	cc *grpc.ClientConn
}

func NewTimedAPBZoneClient(cc *grpc.ClientConn) TimedAPBZoneClient {
	return &timedAPBZoneClient{cc}
}

func (c *timedAPBZoneClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timedAPBZoneClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timedAPBZoneClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timedAPBZoneClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/Clear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timedAPBZoneClient) ClearAll(ctx context.Context, in *ClearAllRequest, opts ...grpc.CallOption) (*ClearAllResponse, error) {
	out := new(ClearAllResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/ClearAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timedAPBZoneClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timedAPBZoneClient) DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error) {
	out := new(DeleteAllResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/DeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timedAPBZoneClient) SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error) {
	out := new(SetAlarmResponse)
	err := c.cc.Invoke(ctx, "/timed_apb_zone.TimedAPBZone/SetAlarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimedAPBZoneServer is the server API for TimedAPBZone service.
type TimedAPBZoneServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Clear(context.Context, *ClearRequest) (*ClearResponse, error)
	ClearAll(context.Context, *ClearAllRequest) (*ClearAllResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteAll(context.Context, *DeleteAllRequest) (*DeleteAllResponse, error)
	SetAlarm(context.Context, *SetAlarmRequest) (*SetAlarmResponse, error)
}

func RegisterTimedAPBZoneServer(s *grpc.Server, srv TimedAPBZoneServer) {
	s.RegisterService(&_TimedAPBZone_serviceDesc, srv)
}

func _TimedAPBZone_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimedAPBZone_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimedAPBZone_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimedAPBZone_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/Clear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimedAPBZone_ClearAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).ClearAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/ClearAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).ClearAll(ctx, req.(*ClearAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimedAPBZone_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimedAPBZone_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).DeleteAll(ctx, req.(*DeleteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimedAPBZone_SetAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedAPBZoneServer).SetAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timed_apb_zone.TimedAPBZone/SetAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedAPBZoneServer).SetAlarm(ctx, req.(*SetAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimedAPBZone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timed_apb_zone.TimedAPBZone",
	HandlerType: (*TimedAPBZoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TimedAPBZone_Get_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _TimedAPBZone_GetStatus_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _TimedAPBZone_Add_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _TimedAPBZone_Clear_Handler,
		},
		{
			MethodName: "ClearAll",
			Handler:    _TimedAPBZone_ClearAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TimedAPBZone_Delete_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _TimedAPBZone_DeleteAll_Handler,
		},
		{
			MethodName: "SetAlarm",
			Handler:    _TimedAPBZone_SetAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timed_apb_zone.proto",
}
