// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wiegand.proto

package wiegand

import (
	device "biostar/service/device"
	err "biostar/service/err"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WiegandMode int32

const (
	WiegandMode_WIEGAND_IN_ONLY  WiegandMode = 0
	WiegandMode_WIEGAND_OUT_ONLY WiegandMode = 1
	WiegandMode_WIEGAND_IN_OUT   WiegandMode = 2
)

var WiegandMode_name = map[int32]string{
	0: "WIEGAND_IN_ONLY",
	1: "WIEGAND_OUT_ONLY",
	2: "WIEGAND_IN_OUT",
}

var WiegandMode_value = map[string]int32{
	"WIEGAND_IN_ONLY":  0,
	"WIEGAND_OUT_ONLY": 1,
	"WIEGAND_IN_OUT":   2,
}

func (x WiegandMode) String() string {
	return proto.EnumName(WiegandMode_name, int32(x))
}

func (WiegandMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{0}
}

type WiegandParity int32

const (
	WiegandParity_WIEGAND_PARITY_NONE WiegandParity = 0
	WiegandParity_WIEGAND_PARITY_ODD  WiegandParity = 1
	WiegandParity_WIEGAND_PARITY_EVEN WiegandParity = 2
)

var WiegandParity_name = map[int32]string{
	0: "WIEGAND_PARITY_NONE",
	1: "WIEGAND_PARITY_ODD",
	2: "WIEGAND_PARITY_EVEN",
}

var WiegandParity_value = map[string]int32{
	"WIEGAND_PARITY_NONE": 0,
	"WIEGAND_PARITY_ODD":  1,
	"WIEGAND_PARITY_EVEN": 2,
}

func (x WiegandParity) String() string {
	return proto.EnumName(WiegandParity_name, int32(x))
}

func (WiegandParity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{1}
}

type ParityField struct {
	ParityPos            uint32        `protobuf:"varint,1,opt,name=parityPos,proto3" json:"parityPos,omitempty"`
	ParityType           WiegandParity `protobuf:"varint,2,opt,name=parityType,proto3,enum=wiegand.WiegandParity" json:"parityType,omitempty"`
	Data                 []byte        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ParityField) Reset()         { *m = ParityField{} }
func (m *ParityField) String() string { return proto.CompactTextString(m) }
func (*ParityField) ProtoMessage()    {}
func (*ParityField) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{0}
}

func (m *ParityField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParityField.Unmarshal(m, b)
}
func (m *ParityField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParityField.Marshal(b, m, deterministic)
}
func (m *ParityField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParityField.Merge(m, src)
}
func (m *ParityField) XXX_Size() int {
	return xxx_messageInfo_ParityField.Size(m)
}
func (m *ParityField) XXX_DiscardUnknown() {
	xxx_messageInfo_ParityField.DiscardUnknown(m)
}

var xxx_messageInfo_ParityField proto.InternalMessageInfo

func (m *ParityField) GetParityPos() uint32 {
	if m != nil {
		return m.ParityPos
	}
	return 0
}

func (m *ParityField) GetParityType() WiegandParity {
	if m != nil {
		return m.ParityType
	}
	return WiegandParity_WIEGAND_PARITY_NONE
}

func (m *ParityField) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WiegandFormat struct {
	FormatID             uint32         `protobuf:"varint,1,opt,name=formatID,proto3" json:"formatID,omitempty"`
	Length               uint32         `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	IDFields             [][]byte       `protobuf:"bytes,3,rep,name=IDFields,proto3" json:"IDFields,omitempty"`
	ParityFields         []*ParityField `protobuf:"bytes,4,rep,name=parityFields,proto3" json:"parityFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WiegandFormat) Reset()         { *m = WiegandFormat{} }
func (m *WiegandFormat) String() string { return proto.CompactTextString(m) }
func (*WiegandFormat) ProtoMessage()    {}
func (*WiegandFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{1}
}

func (m *WiegandFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiegandFormat.Unmarshal(m, b)
}
func (m *WiegandFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiegandFormat.Marshal(b, m, deterministic)
}
func (m *WiegandFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiegandFormat.Merge(m, src)
}
func (m *WiegandFormat) XXX_Size() int {
	return xxx_messageInfo_WiegandFormat.Size(m)
}
func (m *WiegandFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_WiegandFormat.DiscardUnknown(m)
}

var xxx_messageInfo_WiegandFormat proto.InternalMessageInfo

func (m *WiegandFormat) GetFormatID() uint32 {
	if m != nil {
		return m.FormatID
	}
	return 0
}

func (m *WiegandFormat) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *WiegandFormat) GetIDFields() [][]byte {
	if m != nil {
		return m.IDFields
	}
	return nil
}

func (m *WiegandFormat) GetParityFields() []*ParityField {
	if m != nil {
		return m.ParityFields
	}
	return nil
}

type WiegandConfig struct {
	Mode                 WiegandMode      `protobuf:"varint,1,opt,name=mode,proto3,enum=wiegand.WiegandMode" json:"mode,omitempty"`
	UseWiegandBypass     bool             `protobuf:"varint,2,opt,name=useWiegandBypass,proto3" json:"useWiegandBypass,omitempty"`
	UseFailCode          bool             `protobuf:"varint,3,opt,name=useFailCode,proto3" json:"useFailCode,omitempty"`
	FailCode             uint32           `protobuf:"varint,4,opt,name=failCode,proto3" json:"failCode,omitempty"`
	OutPulseWidth        uint32           `protobuf:"varint,5,opt,name=outPulseWidth,proto3" json:"outPulseWidth,omitempty"`
	OutPulseInterval     uint32           `protobuf:"varint,6,opt,name=outPulseInterval,proto3" json:"outPulseInterval,omitempty"`
	Formats              []*WiegandFormat `protobuf:"bytes,7,rep,name=formats,proto3" json:"formats,omitempty"`
	SlaveFormats         []*WiegandFormat `protobuf:"bytes,8,rep,name=slaveFormats,proto3" json:"slaveFormats,omitempty"`
	CSNFormat            *WiegandFormat   `protobuf:"bytes,9,opt,name=CSNFormat,proto3" json:"CSNFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WiegandConfig) Reset()         { *m = WiegandConfig{} }
func (m *WiegandConfig) String() string { return proto.CompactTextString(m) }
func (*WiegandConfig) ProtoMessage()    {}
func (*WiegandConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{2}
}

func (m *WiegandConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiegandConfig.Unmarshal(m, b)
}
func (m *WiegandConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiegandConfig.Marshal(b, m, deterministic)
}
func (m *WiegandConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiegandConfig.Merge(m, src)
}
func (m *WiegandConfig) XXX_Size() int {
	return xxx_messageInfo_WiegandConfig.Size(m)
}
func (m *WiegandConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WiegandConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WiegandConfig proto.InternalMessageInfo

func (m *WiegandConfig) GetMode() WiegandMode {
	if m != nil {
		return m.Mode
	}
	return WiegandMode_WIEGAND_IN_ONLY
}

func (m *WiegandConfig) GetUseWiegandBypass() bool {
	if m != nil {
		return m.UseWiegandBypass
	}
	return false
}

func (m *WiegandConfig) GetUseFailCode() bool {
	if m != nil {
		return m.UseFailCode
	}
	return false
}

func (m *WiegandConfig) GetFailCode() uint32 {
	if m != nil {
		return m.FailCode
	}
	return 0
}

func (m *WiegandConfig) GetOutPulseWidth() uint32 {
	if m != nil {
		return m.OutPulseWidth
	}
	return 0
}

func (m *WiegandConfig) GetOutPulseInterval() uint32 {
	if m != nil {
		return m.OutPulseInterval
	}
	return 0
}

func (m *WiegandConfig) GetFormats() []*WiegandFormat {
	if m != nil {
		return m.Formats
	}
	return nil
}

func (m *WiegandConfig) GetSlaveFormats() []*WiegandFormat {
	if m != nil {
		return m.SlaveFormats
	}
	return nil
}

func (m *WiegandConfig) GetCSNFormat() *WiegandFormat {
	if m != nil {
		return m.CSNFormat
	}
	return nil
}

type GetConfigRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{3}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetConfigResponse struct {
	Config               *WiegandConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{4}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetConfig() *WiegandConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigRequest struct {
	DeviceID             uint32         `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Config               *WiegandConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{5}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetConfigRequest) GetConfig() *WiegandConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{6}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

type SetConfigMultiRequest struct {
	DeviceIDs            []uint32       `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	Config               *WiegandConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetConfigMultiRequest) Reset()         { *m = SetConfigMultiRequest{} }
func (m *SetConfigMultiRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiRequest) ProtoMessage()    {}
func (*SetConfigMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{7}
}

func (m *SetConfigMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiRequest.Unmarshal(m, b)
}
func (m *SetConfigMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiRequest.Merge(m, src)
}
func (m *SetConfigMultiRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiRequest.Size(m)
}
func (m *SetConfigMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiRequest proto.InternalMessageInfo

func (m *SetConfigMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *SetConfigMultiRequest) GetConfig() *WiegandConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetConfigMultiResponse) Reset()         { *m = SetConfigMultiResponse{} }
func (m *SetConfigMultiResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiResponse) ProtoMessage()    {}
func (*SetConfigMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{8}
}

func (m *SetConfigMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiResponse.Unmarshal(m, b)
}
func (m *SetConfigMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiResponse.Merge(m, src)
}
func (m *SetConfigMultiResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiResponse.Size(m)
}
func (m *SetConfigMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiResponse proto.InternalMessageInfo

func (m *SetConfigMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type WiegandTamperInput struct {
	DeviceID             uint32            `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Port                 uint32            `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	SwitchType           device.SwitchType `protobuf:"varint,3,opt,name=switchType,proto3,enum=device.SwitchType" json:"switchType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WiegandTamperInput) Reset()         { *m = WiegandTamperInput{} }
func (m *WiegandTamperInput) String() string { return proto.CompactTextString(m) }
func (*WiegandTamperInput) ProtoMessage()    {}
func (*WiegandTamperInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{9}
}

func (m *WiegandTamperInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiegandTamperInput.Unmarshal(m, b)
}
func (m *WiegandTamperInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiegandTamperInput.Marshal(b, m, deterministic)
}
func (m *WiegandTamperInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiegandTamperInput.Merge(m, src)
}
func (m *WiegandTamperInput) XXX_Size() int {
	return xxx_messageInfo_WiegandTamperInput.Size(m)
}
func (m *WiegandTamperInput) XXX_DiscardUnknown() {
	xxx_messageInfo_WiegandTamperInput.DiscardUnknown(m)
}

var xxx_messageInfo_WiegandTamperInput proto.InternalMessageInfo

func (m *WiegandTamperInput) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *WiegandTamperInput) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *WiegandTamperInput) GetSwitchType() device.SwitchType {
	if m != nil {
		return m.SwitchType
	}
	return device.SwitchType_NORMALLY_OPEN
}

type WiegandOutput struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WiegandOutput) Reset()         { *m = WiegandOutput{} }
func (m *WiegandOutput) String() string { return proto.CompactTextString(m) }
func (*WiegandOutput) ProtoMessage()    {}
func (*WiegandOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{10}
}

func (m *WiegandOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiegandOutput.Unmarshal(m, b)
}
func (m *WiegandOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiegandOutput.Marshal(b, m, deterministic)
}
func (m *WiegandOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiegandOutput.Merge(m, src)
}
func (m *WiegandOutput) XXX_Size() int {
	return xxx_messageInfo_WiegandOutput.Size(m)
}
func (m *WiegandOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_WiegandOutput.DiscardUnknown(m)
}

var xxx_messageInfo_WiegandOutput proto.InternalMessageInfo

func (m *WiegandOutput) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *WiegandOutput) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type WiegandDeviceInfo struct {
	DeviceID             uint32              `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	TamperInput          *WiegandTamperInput `protobuf:"bytes,2,opt,name=tamperInput,proto3" json:"tamperInput,omitempty"`
	RedLEDOutput         *WiegandOutput      `protobuf:"bytes,3,opt,name=redLEDOutput,proto3" json:"redLEDOutput,omitempty"`
	GreenLEDOutput       *WiegandOutput      `protobuf:"bytes,4,opt,name=greenLEDOutput,proto3" json:"greenLEDOutput,omitempty"`
	BuzzerOutput         *WiegandOutput      `protobuf:"bytes,5,opt,name=buzzerOutput,proto3" json:"buzzerOutput,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WiegandDeviceInfo) Reset()         { *m = WiegandDeviceInfo{} }
func (m *WiegandDeviceInfo) String() string { return proto.CompactTextString(m) }
func (*WiegandDeviceInfo) ProtoMessage()    {}
func (*WiegandDeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{11}
}

func (m *WiegandDeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiegandDeviceInfo.Unmarshal(m, b)
}
func (m *WiegandDeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiegandDeviceInfo.Marshal(b, m, deterministic)
}
func (m *WiegandDeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiegandDeviceInfo.Merge(m, src)
}
func (m *WiegandDeviceInfo) XXX_Size() int {
	return xxx_messageInfo_WiegandDeviceInfo.Size(m)
}
func (m *WiegandDeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WiegandDeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WiegandDeviceInfo proto.InternalMessageInfo

func (m *WiegandDeviceInfo) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *WiegandDeviceInfo) GetTamperInput() *WiegandTamperInput {
	if m != nil {
		return m.TamperInput
	}
	return nil
}

func (m *WiegandDeviceInfo) GetRedLEDOutput() *WiegandOutput {
	if m != nil {
		return m.RedLEDOutput
	}
	return nil
}

func (m *WiegandDeviceInfo) GetGreenLEDOutput() *WiegandOutput {
	if m != nil {
		return m.GreenLEDOutput
	}
	return nil
}

func (m *WiegandDeviceInfo) GetBuzzerOutput() *WiegandOutput {
	if m != nil {
		return m.BuzzerOutput
	}
	return nil
}

type SearchDeviceRequest struct {
	ParentDeviceID       uint32   `protobuf:"varint,1,opt,name=parentDeviceID,proto3" json:"parentDeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchDeviceRequest) Reset()         { *m = SearchDeviceRequest{} }
func (m *SearchDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*SearchDeviceRequest) ProtoMessage()    {}
func (*SearchDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{12}
}

func (m *SearchDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDeviceRequest.Unmarshal(m, b)
}
func (m *SearchDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDeviceRequest.Marshal(b, m, deterministic)
}
func (m *SearchDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDeviceRequest.Merge(m, src)
}
func (m *SearchDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_SearchDeviceRequest.Size(m)
}
func (m *SearchDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDeviceRequest proto.InternalMessageInfo

func (m *SearchDeviceRequest) GetParentDeviceID() uint32 {
	if m != nil {
		return m.ParentDeviceID
	}
	return 0
}

type SearchDeviceResponse struct {
	WiegandDeviceIDs     []uint32 `protobuf:"varint,1,rep,packed,name=wiegandDeviceIDs,proto3" json:"wiegandDeviceIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchDeviceResponse) Reset()         { *m = SearchDeviceResponse{} }
func (m *SearchDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*SearchDeviceResponse) ProtoMessage()    {}
func (*SearchDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{13}
}

func (m *SearchDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDeviceResponse.Unmarshal(m, b)
}
func (m *SearchDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDeviceResponse.Marshal(b, m, deterministic)
}
func (m *SearchDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDeviceResponse.Merge(m, src)
}
func (m *SearchDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_SearchDeviceResponse.Size(m)
}
func (m *SearchDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDeviceResponse proto.InternalMessageInfo

func (m *SearchDeviceResponse) GetWiegandDeviceIDs() []uint32 {
	if m != nil {
		return m.WiegandDeviceIDs
	}
	return nil
}

type SetDeviceRequest struct {
	ParentDeviceID       uint32               `protobuf:"varint,1,opt,name=parentDeviceID,proto3" json:"parentDeviceID,omitempty"`
	DeviceInfos          []*WiegandDeviceInfo `protobuf:"bytes,2,rep,name=deviceInfos,proto3" json:"deviceInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetDeviceRequest) Reset()         { *m = SetDeviceRequest{} }
func (m *SetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*SetDeviceRequest) ProtoMessage()    {}
func (*SetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{14}
}

func (m *SetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceRequest.Unmarshal(m, b)
}
func (m *SetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceRequest.Marshal(b, m, deterministic)
}
func (m *SetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceRequest.Merge(m, src)
}
func (m *SetDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_SetDeviceRequest.Size(m)
}
func (m *SetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceRequest proto.InternalMessageInfo

func (m *SetDeviceRequest) GetParentDeviceID() uint32 {
	if m != nil {
		return m.ParentDeviceID
	}
	return 0
}

func (m *SetDeviceRequest) GetDeviceInfos() []*WiegandDeviceInfo {
	if m != nil {
		return m.DeviceInfos
	}
	return nil
}

type SetDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceResponse) Reset()         { *m = SetDeviceResponse{} }
func (m *SetDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*SetDeviceResponse) ProtoMessage()    {}
func (*SetDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{15}
}

func (m *SetDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceResponse.Unmarshal(m, b)
}
func (m *SetDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceResponse.Marshal(b, m, deterministic)
}
func (m *SetDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceResponse.Merge(m, src)
}
func (m *SetDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_SetDeviceResponse.Size(m)
}
func (m *SetDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceResponse proto.InternalMessageInfo

type GetDeviceRequest struct {
	ParentDeviceID       uint32   `protobuf:"varint,1,opt,name=parentDeviceID,proto3" json:"parentDeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceRequest) Reset()         { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()    {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{16}
}

func (m *GetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceRequest.Unmarshal(m, b)
}
func (m *GetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceRequest.Merge(m, src)
}
func (m *GetDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceRequest.Size(m)
}
func (m *GetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceRequest proto.InternalMessageInfo

func (m *GetDeviceRequest) GetParentDeviceID() uint32 {
	if m != nil {
		return m.ParentDeviceID
	}
	return 0
}

type GetDeviceResponse struct {
	DeviceInfos          []*WiegandDeviceInfo `protobuf:"bytes,1,rep,name=deviceInfos,proto3" json:"deviceInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDeviceResponse) Reset()         { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()    {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5f45a615a2ff8a, []int{17}
}

func (m *GetDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceResponse.Unmarshal(m, b)
}
func (m *GetDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceResponse.Merge(m, src)
}
func (m *GetDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceResponse.Size(m)
}
func (m *GetDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceResponse proto.InternalMessageInfo

func (m *GetDeviceResponse) GetDeviceInfos() []*WiegandDeviceInfo {
	if m != nil {
		return m.DeviceInfos
	}
	return nil
}

func init() {
	proto.RegisterEnum("wiegand.WiegandMode", WiegandMode_name, WiegandMode_value)
	proto.RegisterEnum("wiegand.WiegandParity", WiegandParity_name, WiegandParity_value)
	proto.RegisterType((*ParityField)(nil), "wiegand.ParityField")
	proto.RegisterType((*WiegandFormat)(nil), "wiegand.WiegandFormat")
	proto.RegisterType((*WiegandConfig)(nil), "wiegand.WiegandConfig")
	proto.RegisterType((*GetConfigRequest)(nil), "wiegand.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "wiegand.GetConfigResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "wiegand.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "wiegand.SetConfigResponse")
	proto.RegisterType((*SetConfigMultiRequest)(nil), "wiegand.SetConfigMultiRequest")
	proto.RegisterType((*SetConfigMultiResponse)(nil), "wiegand.SetConfigMultiResponse")
	proto.RegisterType((*WiegandTamperInput)(nil), "wiegand.WiegandTamperInput")
	proto.RegisterType((*WiegandOutput)(nil), "wiegand.WiegandOutput")
	proto.RegisterType((*WiegandDeviceInfo)(nil), "wiegand.WiegandDeviceInfo")
	proto.RegisterType((*SearchDeviceRequest)(nil), "wiegand.SearchDeviceRequest")
	proto.RegisterType((*SearchDeviceResponse)(nil), "wiegand.SearchDeviceResponse")
	proto.RegisterType((*SetDeviceRequest)(nil), "wiegand.SetDeviceRequest")
	proto.RegisterType((*SetDeviceResponse)(nil), "wiegand.SetDeviceResponse")
	proto.RegisterType((*GetDeviceRequest)(nil), "wiegand.GetDeviceRequest")
	proto.RegisterType((*GetDeviceResponse)(nil), "wiegand.GetDeviceResponse")
}

func init() { proto.RegisterFile("wiegand.proto", fileDescriptor_6f5f45a615a2ff8a) }

var fileDescriptor_6f5f45a615a2ff8a = []byte{
	// 940 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xef, 0x4e, 0xe3, 0x46,
	0x10, 0x3f, 0x27, 0x39, 0x20, 0x93, 0x3f, 0x35, 0x03, 0xe5, 0x5c, 0x97, 0xb6, 0x91, 0x55, 0x55,
	0x11, 0x1f, 0x72, 0x55, 0x5a, 0x5d, 0xab, 0x53, 0xaf, 0xd5, 0x85, 0x04, 0x14, 0x95, 0x4b, 0x72,
	0x4e, 0xae, 0x27, 0xfa, 0xa1, 0xc8, 0xc4, 0x0b, 0x58, 0x4d, 0x6c, 0x77, 0xd7, 0x86, 0xe3, 0xde,
	0x84, 0x17, 0xe8, 0x3b, 0xf4, 0xed, 0x2a, 0xef, 0xae, 0x1d, 0xdb, 0x09, 0xd1, 0xc1, 0x27, 0xbc,
	0xbf, 0xf9, 0xcd, 0x6f, 0x66, 0x67, 0x67, 0x26, 0x40, 0xed, 0xc6, 0x21, 0x97, 0x96, 0x6b, 0xb7,
	0x7c, 0xea, 0x05, 0x1e, 0x6e, 0xca, 0xa3, 0x5e, 0xb5, 0xc9, 0xb5, 0x33, 0x25, 0x02, 0xd6, 0xcb,
	0x84, 0x52, 0xf1, 0x69, 0xdc, 0x40, 0x65, 0x64, 0x51, 0x27, 0xb8, 0x3d, 0x72, 0xc8, 0xcc, 0xc6,
	0x7d, 0x28, 0xfb, 0xfc, 0x38, 0xf2, 0x98, 0xa6, 0x34, 0x94, 0x66, 0xcd, 0x5c, 0x00, 0xf8, 0x02,
	0x40, 0x1c, 0x26, 0xb7, 0x3e, 0xd1, 0x0a, 0x0d, 0xa5, 0x59, 0x6f, 0xef, 0xb5, 0xe2, 0x90, 0xef,
	0xc5, 0x5f, 0x21, 0x67, 0xa6, 0x98, 0x88, 0x50, 0xb2, 0xad, 0xc0, 0xd2, 0x8a, 0x0d, 0xa5, 0x59,
	0x35, 0xf9, 0xb7, 0x71, 0xa7, 0x40, 0x4d, 0x7a, 0x1c, 0x79, 0x74, 0x6e, 0x05, 0xa8, 0xc3, 0xd6,
	0x05, 0xff, 0xea, 0x77, 0x65, 0xe8, 0xe4, 0x8c, 0x7b, 0xb0, 0x31, 0x23, 0xee, 0x65, 0x70, 0xc5,
	0xa3, 0xd6, 0x4c, 0x79, 0x8a, 0x7c, 0xfa, 0x5d, 0x9e, 0x3a, 0xd3, 0x8a, 0x8d, 0x62, 0xb3, 0x6a,
	0x26, 0x67, 0xfc, 0x19, 0xaa, 0xfe, 0xe2, 0x6a, 0x4c, 0x2b, 0x35, 0x8a, 0xcd, 0x4a, 0x7b, 0x37,
	0xc9, 0x37, 0x75, 0x6f, 0x33, 0xc3, 0x34, 0xee, 0x8a, 0x49, 0x6e, 0x87, 0x9e, 0x7b, 0xe1, 0x5c,
	0x62, 0x13, 0x4a, 0x73, 0xcf, 0x26, 0x3c, 0xaf, 0x7a, 0x4a, 0x43, 0xb2, 0xde, 0x78, 0x36, 0x31,
	0x39, 0x03, 0x0f, 0x40, 0x0d, 0x19, 0x91, 0x78, 0xe7, 0xd6, 0xb7, 0x18, 0xe3, 0x39, 0x6f, 0x99,
	0x4b, 0x38, 0x36, 0xa0, 0x12, 0x32, 0x72, 0x64, 0x39, 0xb3, 0xc3, 0x48, 0xbc, 0xc8, 0x69, 0x69,
	0x88, 0xd7, 0x24, 0x36, 0x97, 0x64, 0x4d, 0x62, 0xdb, 0xb7, 0x50, 0xf3, 0xc2, 0x60, 0x14, 0xce,
	0x22, 0x59, 0x3b, 0xb8, 0xd2, 0x9e, 0x72, 0x42, 0x16, 0x8c, 0xf2, 0x89, 0x81, 0xbe, 0x1b, 0x10,
	0x7a, 0x6d, 0xcd, 0xb4, 0x0d, 0x4e, 0x5c, 0xc2, 0xf1, 0x7b, 0xd8, 0x14, 0x15, 0x67, 0xda, 0x26,
	0x2f, 0xd6, 0xd2, 0xe3, 0x8a, 0xa7, 0x32, 0x63, 0x1a, 0xbe, 0x84, 0x2a, 0x9b, 0x59, 0xd7, 0xe4,
	0x48, 0xba, 0x6d, 0xad, 0x75, 0xcb, 0x70, 0xf1, 0x47, 0x28, 0x1f, 0x8e, 0x07, 0xe2, 0xa4, 0x95,
	0x1b, 0xca, 0x1a, 0xc7, 0x05, 0xd1, 0x68, 0x81, 0x7a, 0x4c, 0x02, 0xf1, 0x2c, 0x26, 0xf9, 0x27,
	0x24, 0x8c, 0x77, 0x8e, 0xe8, 0xef, 0x45, 0xe7, 0xc4, 0x67, 0xe3, 0x10, 0xb6, 0x53, 0x7c, 0xe6,
	0x7b, 0x2e, 0x23, 0xd8, 0x82, 0x8d, 0x29, 0x47, 0x38, 0x7d, 0x45, 0x5c, 0xc9, 0x97, 0x2c, 0xe3,
	0x2f, 0x50, 0xc7, 0x0f, 0x08, 0x9a, 0xd2, 0x2f, 0x7c, 0x92, 0xfe, 0x0e, 0x6c, 0x8f, 0xf3, 0x49,
	0x1a, 0x04, 0x3e, 0x4f, 0xc0, 0x37, 0xe1, 0x2c, 0x70, 0xe2, 0xc8, 0xfb, 0x50, 0x8e, 0x23, 0x45,
	0x43, 0x5a, 0x8c, 0x86, 0x34, 0x01, 0x1e, 0x1c, 0x7b, 0x04, 0x7b, 0xf9, 0x30, 0xb2, 0x4a, 0x2f,
	0x40, 0xae, 0x8d, 0x1e, 0xa5, 0x1e, 0x15, 0xa1, 0x2a, 0x6d, 0x6c, 0x45, 0xdb, 0x83, 0x43, 0x31,
	0xd3, 0xcc, 0xf0, 0x8c, 0x0f, 0x80, 0x32, 0xd4, 0xc4, 0x9a, 0xfb, 0x84, 0xf6, 0x5d, 0x3f, 0x5c,
	0x5f, 0x2f, 0x84, 0x92, 0xef, 0xd1, 0x40, 0x0e, 0x37, 0xff, 0xc6, 0x36, 0x00, 0xbb, 0x71, 0x82,
	0xe9, 0x15, 0x5f, 0x36, 0x45, 0x3e, 0x78, 0xd8, 0x92, 0x7b, 0x6c, 0x9c, 0x58, 0xcc, 0x14, 0xcb,
	0xf8, 0x2d, 0x99, 0xdb, 0x61, 0x18, 0x3c, 0x22, 0xa8, 0xf1, 0x6f, 0x01, 0xb6, 0xa5, 0x42, 0x57,
	0xf0, 0xdc, 0x0b, 0x6f, 0xad, 0xca, 0x2b, 0xa8, 0x04, 0x8b, 0x5b, 0xca, 0x9a, 0x7f, 0x99, 0xaf,
	0x79, 0xaa, 0x10, 0x66, 0x9a, 0x1f, 0x0d, 0x10, 0x25, 0xf6, 0x49, 0xaf, 0x2b, 0x12, 0xe6, 0xf7,
	0x5c, 0xf1, 0x66, 0xc2, 0x6a, 0x66, 0xb8, 0xf8, 0x2b, 0xd4, 0x2f, 0x29, 0x21, 0xee, 0xc2, 0xbb,
	0xb4, 0xd6, 0x3b, 0xc7, 0x8e, 0x62, 0x9f, 0x87, 0x1f, 0x3f, 0x12, 0x2a, 0xbd, 0x9f, 0xae, 0x8f,
	0x9d, 0xe6, 0x1a, 0xaf, 0x60, 0x67, 0x4c, 0x2c, 0x3a, 0xbd, 0x12, 0x65, 0x8a, 0x5b, 0xf3, 0x3b,
	0xa8, 0xfb, 0x16, 0x25, 0x6e, 0xd0, 0xcd, 0xd6, 0x2b, 0x87, 0x1a, 0x1d, 0xd8, 0xcd, 0xba, 0xcb,
	0x96, 0x3b, 0x00, 0xf5, 0x26, 0x53, 0xfe, 0xa4, 0xc3, 0x97, 0x70, 0xe3, 0x03, 0x1f, 0xca, 0x47,
	0xc5, 0xc7, 0x5f, 0xa0, 0x62, 0x27, 0xef, 0x1b, 0x2d, 0xe8, 0xa8, 0xb3, 0xf5, 0xfc, 0xcd, 0x17,
	0x2d, 0x60, 0xa6, 0xe9, 0x72, 0x5c, 0xb3, 0xa9, 0x1b, 0x2f, 0xf9, 0x62, 0x7a, 0x5c, 0x39, 0xde,
	0xf2, 0x25, 0x95, 0xab, 0x45, 0x2e, 0x47, 0xe5, 0x41, 0x39, 0x1e, 0x9c, 0x40, 0x25, 0xf5, 0xe3,
	0x84, 0x3b, 0xf0, 0xd9, 0xfb, 0x7e, 0xef, 0xf8, 0xf5, 0xa0, 0x7b, 0xd6, 0x1f, 0x9c, 0x0d, 0x07,
	0x27, 0xa7, 0xea, 0x13, 0xdc, 0x05, 0x35, 0x06, 0x87, 0xef, 0x26, 0x02, 0x55, 0x10, 0xa1, 0x9e,
	0xa6, 0xbe, 0x9b, 0xa8, 0x85, 0x83, 0xd3, 0x64, 0xb0, 0xc4, 0xaf, 0x26, 0x3e, 0x83, 0x9d, 0x98,
	0x34, 0x7a, 0x6d, 0xf6, 0x27, 0xa7, 0x67, 0x83, 0xe1, 0xa0, 0xa7, 0x3e, 0xc1, 0x3d, 0xc0, 0x9c,
	0x61, 0xd8, 0xed, 0xaa, 0xca, 0x0a, 0x87, 0xde, 0x1f, 0xbd, 0x81, 0x5a, 0x68, 0xff, 0x57, 0x84,
	0x4d, 0xa9, 0x8d, 0x1d, 0x28, 0x27, 0xcb, 0x1a, 0xbf, 0x48, 0xae, 0x9a, 0x5f, 0xf8, 0xba, 0xbe,
	0xca, 0x24, 0xcb, 0xd6, 0x81, 0xf2, 0x78, 0x85, 0xc6, 0xf8, 0x7e, 0x8d, 0xa5, 0xd5, 0x8b, 0x6f,
	0xa1, 0x9e, 0xdd, 0x89, 0xf8, 0xf5, 0x32, 0x3b, 0xbd, 0x93, 0xf5, 0x6f, 0xee, 0xb5, 0x4b, 0xc9,
	0xdf, 0xa1, 0x9a, 0xee, 0x78, 0xdc, 0x4f, 0x39, 0x2c, 0xcd, 0x91, 0xfe, 0xd5, 0x3d, 0xd6, 0xcc,
	0x1d, 0xa5, 0x52, 0xe6, 0x8e, 0x59, 0x19, 0x7d, 0x95, 0x69, 0xa1, 0x71, 0xbc, 0x42, 0xe3, 0xf8,
	0x7e, 0x8d, 0xa5, 0x16, 0xed, 0xfc, 0x04, 0xfa, 0xd4, 0x9b, 0xb7, 0x58, 0xe8, 0x53, 0x32, 0xb7,
	0x1c, 0x77, 0xda, 0x62, 0xf6, 0xdf, 0x31, 0x7f, 0xa4, 0xfc, 0xf9, 0xec, 0xdc, 0xf1, 0x58, 0x60,
	0xd1, 0xe7, 0x8c, 0xd0, 0xc8, 0xf1, 0xb9, 0x34, 0x9d, 0x6f, 0xf0, 0xff, 0x3e, 0x7f, 0xf8, 0x3f,
	0x00, 0x00, 0xff, 0xff, 0x6f, 0x1d, 0xe1, 0x96, 0xb0, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WiegandClient is the client API for Wiegand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WiegandClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error)
	SearchDevice(ctx context.Context, in *SearchDeviceRequest, opts ...grpc.CallOption) (*SearchDeviceResponse, error)
	SetDevice(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*SetDeviceResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
}

type wiegandClient struct {
	cc *grpc.ClientConn
}

func NewWiegandClient(cc *grpc.ClientConn) WiegandClient {
	return &wiegandClient{cc}
}

func (c *wiegandClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/wiegand.Wiegand/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiegandClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/wiegand.Wiegand/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiegandClient) SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error) {
	out := new(SetConfigMultiResponse)
	err := c.cc.Invoke(ctx, "/wiegand.Wiegand/SetConfigMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiegandClient) SearchDevice(ctx context.Context, in *SearchDeviceRequest, opts ...grpc.CallOption) (*SearchDeviceResponse, error) {
	out := new(SearchDeviceResponse)
	err := c.cc.Invoke(ctx, "/wiegand.Wiegand/SearchDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiegandClient) SetDevice(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*SetDeviceResponse, error) {
	out := new(SetDeviceResponse)
	err := c.cc.Invoke(ctx, "/wiegand.Wiegand/SetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiegandClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/wiegand.Wiegand/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WiegandServer is the server API for Wiegand service.
type WiegandServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	SetConfigMulti(context.Context, *SetConfigMultiRequest) (*SetConfigMultiResponse, error)
	SearchDevice(context.Context, *SearchDeviceRequest) (*SearchDeviceResponse, error)
	SetDevice(context.Context, *SetDeviceRequest) (*SetDeviceResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
}

func RegisterWiegandServer(s *grpc.Server, srv WiegandServer) {
	s.RegisterService(&_Wiegand_serviceDesc, srv)
}

func _Wiegand_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiegandServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiegand.Wiegand/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiegandServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiegand_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiegandServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiegand.Wiegand/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiegandServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiegand_SetConfigMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiegandServer).SetConfigMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiegand.Wiegand/SetConfigMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiegandServer).SetConfigMulti(ctx, req.(*SetConfigMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiegand_SearchDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiegandServer).SearchDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiegand.Wiegand/SearchDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiegandServer).SearchDevice(ctx, req.(*SearchDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiegand_SetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiegandServer).SetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiegand.Wiegand/SetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiegandServer).SetDevice(ctx, req.(*SetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wiegand_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiegandServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiegand.Wiegand/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiegandServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wiegand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wiegand.Wiegand",
	HandlerType: (*WiegandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _Wiegand_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Wiegand_SetConfig_Handler,
		},
		{
			MethodName: "SetConfigMulti",
			Handler:    _Wiegand_SetConfigMulti_Handler,
		},
		{
			MethodName: "SearchDevice",
			Handler:    _Wiegand_SearchDevice_Handler,
		},
		{
			MethodName: "SetDevice",
			Handler:    _Wiegand_SetDevice_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _Wiegand_GetDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wiegand.proto",
}
